export const ELEMENTS={EMBER:{name:'Ember',color:'#ff7438',effect:'burns'},FROST:{name:'Frost',color:'#42e4c4',effect:'slows'},ARC:{name:'Arc',color:'#74cfff',effect:'chains and stuns'},STEAM:{name:'Steam',color:'#c6b7e8',effect:'knocks back'}};
export const SHAPES={
 CLOSEHIT:{name:'Cleave',kind:'arc',damage:22,cd:.45,range:190},LINE_BURST:{name:'Lance',kind:'line',damage:30,cd:1.1,range:520},CONE:{name:'Gale',kind:'cone',damage:26,cd:1.4,range:300},RANGED_AOE:{name:'Mortar',kind:'aoe',damage:40,cd:2.6,range:420},CHAIN:{name:'Whip',kind:'chain',damage:26,cd:2,range:480},AURA:{name:'Field',kind:'aura',damage:4,cd:0,range:150,passive:true},PULSE:{name:'Pulse',kind:'pulse',damage:34,cd:4.4,range:210,passive:true},SENTRY:{name:'Sentry',kind:'sentry',damage:14,cd:9,range:520},RAY:{name:'Beam',kind:'ray',damage:7,cd:.6,range:480}
};
export const ENEMIES={SCRAPPER:{hp:60,speed:70,damage:12,r:18,color:'#c98347'},GUNNER:{hp:35,speed:52,damage:10,r:16,color:'#d8b760',range:270},ARMORED:{hp:180,speed:38,damage:20,r:25,color:'#b45d43'},SWARM:{hp:20,speed:108,damage:6,r:12,color:'#d39d50'},BOSS:{hp:900,speed:44,damage:26,r:52,color:'#dc4d37'}};
export const WAVES=[
 {S:8},{S:8,W:4},{S:8,G:5},{event:'grapple',S:10,A:3},{S:14,G:5},{S:12,W:8,A:3},{S:16,G:8,A:4},{event:'blackout',S:12,G:10,A:5},{S:20,G:8,A:6},{S:18,W:14,A:6},{S:22,G:12,A:7},{event:'colossus',B:1,S:12,G:6}
];
export const EVENTS={grapple:{name:'GRAPPLE RUN',text:'A boarding hulk has locked on at the bow. Break it or it keeps unloading.'},blackout:{name:'BOILER BLACKOUT',text:'The lamps are out and the gauge is cold. Salvage pays double while it lasts.'},colossus:{name:'THE COLOSSUS',text:'It turns at half health. Survive both beats.'}};
export const CLASSES={
 captain:{name:'The Captain',tag:'Close the distance. Spend pressure.',hp:100,speed:245,resource:'PRESSURE',abilities:['Vent at full pressure: blast, heal, knockback','Two dash charges; close kills recover them']},
 boilerwright:{name:'The Boilerwright',tag:'Hold ground. Bank Head at deck vents.',hp:115,speed:165,resource:'HEAD',abilities:['Stand on lit vents to build Head','F Tap Main · V Blowdown · slower, tougher']}
};
export const HEAT=[
 {name:'STOKED',text:'the deck as it was built.'},{name:'RUST',text:'boarders harden faster.',hp:.09},{name:'SHORT FUSE',text:'and attacks wind up faster.',hp:.09,wind:.85},{name:'COLD DECK',text:'and drafts deal two cards with one reroll.',hp:.09,wind:.85,cards:2,rerolls:1},{name:'BOARDERS ALOFT',text:'and hulks grapple on waves 6 and 10.',hp:.09,wind:.85,cards:2,rerolls:1,push:[6,10]},{name:'SKELETON CREW',text:'and no crew musters; cannons begin damaged.',hp:.09,wind:.85,cards:2,rerolls:1,push:[6,10],noCrew:true}
];
export const FITTINGS={wreck:{name:'THE WRECK',rule:'Defeat the Colossus',text:'A permanent trophy and hard cover off the bow.'},barricade:{name:'BOW BARRICADE',rule:'Reach wave 8',text:'Crates guard the middle bow lane.'},spareGun:{name:'THE SPARE GUN',rule:'Win at Heat 1+',text:'A fourth cannon begins broken; repair it.'},fourthVent:{name:'FOURTH VENT',rule:'Win as Boilerwright',text:'A new Head source in the bow crossing.'},winch:{name:'THE WINCH',rule:'Gather 12 salvage',text:'Haul crate stacks to reshape your cover.'},scupper:{name:'SCUPPER GRATING',rule:'Win without healing',text:'Seals a crossing and adds a vent.'}};
export const TALENTS={
 boiler:{name:'Boiler Plate',branch:'SHIP',cost:4,ranks:3,text:'+35 Boiler hull per rank'},stride:{name:'Long Stride',branch:'CAPTAIN',cost:4,ranks:3,text:'+3% move speed per rank'},edge:{name:'Honed Edge',branch:'ARSENAL',cost:5,ranks:3,text:'+4% skill damage per rank'},crew:{name:'Full Muster',branch:'DECK',cost:5,ranks:2,text:'+1 crew per rank'},pressure:{name:'Hot Gauge',branch:'CAPTAIN',cost:6,ranks:2,text:'+8% resource gain per rank'},cannon:{name:'Fine Powder',branch:'DECK',cost:6,ranks:2,text:'+10% cannon damage per rank'},reach:{name:'Long Reach',branch:'ARSENAL',cost:7,ranks:2,text:'+5% range per rank'},salvage:{name:'Claim Rights',branch:'SHIP',cost:7,ranks:2,text:'+1 starting salvage per rank'}
};
export const ARTICLES={pressGang:{name:'Press-Gang',cost:1,text:'Close kills sometimes raise crew.'},secondShift:{name:'Second Shift',cost:2,text:'The first killing blow leaves you at 1.'},deadman:{name:"Deadman's Switch",cost:2,text:'Below a quarter, the Boiler vents once per wave.'},brace:{name:'Brace',cost:1,text:'F · brief invulnerability (Captain).',captain:true},recall:{name:'Recall',cost:2,text:'F · return to the Boiler (Captain).',captain:true},scuttle:{name:'Scuttle',cost:2,text:'V · light every keg once a wave.',captain:true}};
export const CARD_NAMES=['LONG REACH','QUICKENED GEARS','HEAVY CHARGE','WIDE PATTERN','BLOODSTEAM','OVERPRESSURE','SLEDGE FORCE','SPARE PARTS','POWDER STORE','FIELD DRESSING','JURY-RIGGED','ELEMENTAL TEMPER'];
export const makeSkill=(shape,element)=>({shape,element,cd:0,mods:{damage:1,range:1,cooldown:1}});
