import {ELEMENTS,SHAPES,ENEMIES,WAVES,EVENTS,CLASSES,HEAT,FITTINGS,TALENTS,ARTICLES,CARD_NAMES,makeSkill} from './data.js';

const $=s=>document.querySelector(s), canvas=$('#game'), ctx=canvas.getContext('2d'), screen=$('#screen'), toastEl=$('#toast');
const W=1600,H=900,LANES=[480,800,1120],SAVE_KEY='skygear.browser2d.v1';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t, dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const hash=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
class RNG{constructor(seed){this.s=hash(seed)||1}next(){this.s^=this.s<<13;this.s^=this.s>>>17;this.s^=this.s<<5;return(this.s>>>0)/4294967296}pick(a){return a[Math.floor(this.next()*a.length)]}}

const freshSave=()=>({unlocked:false,scrip:0,sigils:0,spentSigils:0,nodes:{},articles:{},firsts:{},fittings:{},berths:[],heat:0,bestHeat:0,runs:[],settings:{volume:.7,reducedMotion:false,keys:{up:'w',down:'s',left:'a',right:'d',dash:' ',interact:'r',ability:'f',blowdown:'v'}}});
function loadSave(){try{return mergeSave(JSON.parse(localStorage.getItem(SAVE_KEY)||'null'))}catch{return freshSave()}}
function mergeSave(raw){const f=freshSave();if(!raw)return f;return{...f,...raw,nodes:{...f.nodes,...raw.nodes},articles:{...f.articles,...raw.articles},firsts:{...f.firsts,...raw.firsts},fittings:{...f.fittings,...raw.fittings},settings:{...f.settings,...raw.settings,keys:{...f.settings.keys,...raw.settings?.keys}}}}
let meta=loadSave(), rng=new RNG('SKYGEAR'), mode='title', last=0, mouse={x:800,y:300,down:[false,false,false]}, keys=new Set(), audio=null;
const game={};

function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(meta))}
function toast(text){toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.classList.remove('show'),1800)}
function btn(label,fn,cls=''){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=fn;return b}
function setScreen(html='',active=true){screen.innerHTML=html;screen.classList.toggle('active',active)}
function addButtons(rows){for(const [label,fn,cls] of rows)screen.querySelector('[data-actions]').append(btn(label,fn,cls))}
function seedText(){return new URLSearchParams(location.search).get('seed')||Math.random().toString(36).slice(2,8).toUpperCase()}
function sfx(freq=220,dur=.05){if(!meta.settings.volume)return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.value=.035*meta.settings.volume;o.connect(g).connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.stop(audio.currentTime+dur)}catch{}}

function showTitle(){mode='title';setScreen(`<div class="panel"><div class="eyebrow">Browser 2D · Godot feature line</div><h1>SKYGEAR</h1><p class="sub">Hold three lanes aboard a storm-running airship. Build a four-skill hand from 36 shape × element combinations, keep the Boiler alive through twelve waves, and make the ship yours between runs.</p><div class="hint">WASD move · mouse aim · LMB/RMB/Q/E skills · Space dash · R deckwork · Esc pause</div><div class="row" data-actions></div><p class="tiny">Persistent progression stays in this browser. Seeded run: <span class="stat">?seed=SKY123</span></p></div>`);addButtons([['DEPLOY',showClass,'primary'],...(meta.unlocked?[[`HEAT  · `,()=>{meta.heat=(meta.heat+1)%(Math.min(HEAT.length,meta.bestHeat+2));save();showTitle()}],['WORKSHOP',showWorkshop],['THE BERTHS',showBerths],['RUN LOG',showLog]]:[]),['SETTINGS',showSettings]])}
function showClass(){mode='class';setScreen(`<div class="panel"><div class="eyebrow">Choose who holds the deck</div><h2>THE ARTICLES OF COMMAND</h2><div class="grid" id="classes"></div><div class="row" data-actions></div></div>`);const box=$('#classes');for(const [id,c] of Object.entries(CLASSES)){const d=document.createElement('button');d.className='card';d.innerHTML=`<div class="tag">${c.resource}</div><h3>${c.name}</h3><p>${c.tag}</p><p>${c.abilities.join('<br>')}</p>`;d.onclick=()=>showLoadout(id);box.append(d)}addButtons([['BACK',showTitle]])}
function showLoadout(classId){mode='loadout';if(!Array.isArray(game.picks))game.picks=[];game.classId=classId;setScreen(`<div class="panel"><div class="eyebrow">Opening weapons · choose two</div><h2>THE OPEN MATRIX</h2><p class="sub">Cleave is always your automatic basic attack. Pick two active tools; the draft fills the rest.</p><div class="matrix" id="matrix"><b>SHAPE</b>${Object.values(ELEMENTS).map(e=>`<b style="color:${e.color}">${e.name}</b>`).join('')}</div><div class="row"><span id="picked">0 / 2 chosen</span></div><div class="row" data-actions></div></div>`);const m=$('#matrix');for(const [sk,s] of Object.entries(SHAPES)){m.insertAdjacentHTML('beforeend',`<b>${s.name}</b>`);for(const [ek,e] of Object.entries(ELEMENTS)){const b=btn(`${s.name} · ${e.name}`,()=>{const k=`${sk}:${ek}`,i=game.picks.indexOf(k);if(i>=0)game.picks.splice(i,1);else if(game.picks.length<2)game.picks.push(k);showLoadout(classId)});if(game.picks.includes(`${sk}:${ek}`))b.className='primary';m.append(b)}}addButtons([['BACK',showClass],['SET SAIL',()=>startRun(classId),game.picks.length===2?'primary':'']]);screen.querySelector('[data-actions] button:last-child').disabled=game.picks.length!==2;$('#picked').textContent=`${game.picks.length} / 2 chosen`}

function talent(id){return meta.nodes[id]||0}
function startRun(classId){const seed=seedText();rng=new RNG(seed);const cls=CLASSES[classId],hp=cls.hp;Object.assign(game,{seed,classId,heat:meta.unlocked?meta.heat:0,wave:0,time:0,score:0,salvage:talent('salvage'),healed:0,vents:0,kills:0,damage:0,deckDamage:0,rerolls:HEAT[meta.heat]?.rerolls??2,player:{x:800,y:700,vx:0,vy:0,hp,maxHp:hp,speed:cls.speed*(1+talent('stride')*.03),dash:2,dashCd:0,inv:0,resource:0},boiler:{x:800,y:790,hp:500+talent('boiler')*35,maxHp:500+talent('boiler')*35},enemies:[],shots:[],fx:[],allies:[],props:[],turrets:[],skills:[makeSkill('CLOSEHIT','EMBER')],spawn:[],spawnClock:0,waveClock:0,autoCd:0,event:'',eventTimer:0,hulk:null,blackout:false,secondShift:false,deadman:false,runDone:false});for(const p of game.picks){const[s,e]=p.split(':');game.skills.push(makeSkill(s,e))}while(game.skills.length<4)game.skills.push(makeSkill('LINE_BURST',rng.pick(Object.keys(ELEMENTS))));restow(true);startWave(1);mode='play';setScreen('',false);toast(`${CLASSES[classId].name} · ${seed}`)}
function restow(initial=false){game.props=[];const crates=[[345,280],[620,390],[980,410],[1245,300]],kegs=[[390,570],[690,250],[930,590],[1190,250]],vents=[[500,700],[800,480],[1100,700]];for(const[x,y]of crates)game.props.push({kind:'crate',x,y,hp:65,maxHp:65,r:30});for(const[x,y]of kegs)game.props.push({kind:'keg',x,y,hp:34,maxHp:34,r:22,fuse:0});for(const[x,y]of vents)game.props.push({kind:'vent',x,y,hp:999,maxHp:999,r:24});const b=meta.berths;if(b.includes('fourthVent'))game.props.push({kind:'vent',x:800,y:215,hp:999,maxHp:999,r:24});if(b.includes('barricade'))for(const x of[730,800,870])game.props.push({kind:'crate',x,y:155,hp:65,maxHp:65,r:30});if(b.includes('wreck'))game.props.push({kind:'wreck',x:1280,y:115,hp:999,maxHp:999,r:55});if(b.includes('scupper'))game.props.push({kind:'vent',x:640,y:510,hp:999,maxHp:999,r:24});if(initial){const hp=HEAT[game.heat]?.noCrew?50:100;game.turrets=LANES.map((x,l)=>({x,y:735,l,hp,maxHp:100,cd:0}));if(b.includes('spareGun'))game.turrets.push({x:1320,y:735,l:2,hp:0,maxHp:100,cd:0})}}
function startWave(n){game.wave=n;game.waveClock=0;game.spawnClock=1;game.event=WAVES[n-1].event||((HEAT[game.heat]?.push||[]).includes(n)?'grapple':'');game.blackout=game.event==='blackout';game.eventTimer=game.event?2.8:0;game.deadman=false;for(const s of game.skills)s.cd=0;const w=WAVES[n-1],map={S:'SCRAPPER',G:'GUNNER',A:'ARMORED',W:'SWARM',B:'BOSS'};game.spawn=[];for(const[k,type]of Object.entries(map))for(let i=0;i<(w[k]||0);i++)game.spawn.push({type,at:i*.23+rng.next()*.45,lane:Math.floor(rng.next()*3)});game.spawn.sort((a,b)=>a.at-b.at);if(game.event==='grapple')game.hulk={x:800,y:68,hp:360+n*25,maxHp:360+n*25};toast(game.event?EVENTS[game.event].name:`WAVE ${n}`)}
function spawnEnemy(q){const d=ENEMIES[q.type],scale=1+(game.wave-1)*(HEAT[game.heat]?.hp??.06);game.enemies.push({type:q.type,lane:q.lane,x:LANES[q.lane]+(rng.next()-.5)*100,y:70,hp:d.hp*scale,maxHp:d.hp*scale,r:d.r,cd:.4+rng.next(),phase:0,slow:0,burn:0,dead:false})}

function update(dt){if(mode!=='play')return;game.time+=dt;game.waveClock+=dt;const p=game.player,k=meta.settings.keys;p.inv=Math.max(0,p.inv-dt);p.dashCd=Math.max(0,p.dashCd-dt);let dx=(keys.has(k.right)?1:0)-(keys.has(k.left)?1:0),dy=(keys.has(k.down)?1:0)-(keys.has(k.up)?1:0),n=Math.hypot(dx,dy)||1;p.vx=lerp(p.vx,dx/n*p.speed,clamp(dt*12,0,1));p.vy=lerp(p.vy,dy/n*p.speed,clamp(dt*12,0,1));p.x=clamp(p.x+p.vx*dt,225,1375);p.y=clamp(p.y+p.vy*dt,90,820);for(const s of game.skills)s.cd=Math.max(0,s.cd-dt);game.autoCd-=dt;if(game.autoCd<=0){const e=nearest(p,game.enemies.filter(x=>!x.dead),190);if(e){deal(e,22,'Cleave');game.autoCd=.45;sfx(120)}}
 if(game.classId==='captain'){const close=game.enemies.filter(e=>!e.dead&&dist(e,p)<190).length;p.resource=clamp(p.resource+close*dt*2.5*(1+talent('pressure')*.08),0,100)}else{const onVent=game.props.some(v=>v.kind==='vent'&&dist(v,p)<68);if(onVent){p.resource=clamp(p.resource+18*dt*(1+talent('pressure')*.08),0,100);game.vents+=dt}}
 game.spawnClock+=dt;while(game.spawn.length&&game.spawn[0].at<=game.waveClock)spawnEnemy(game.spawn.shift());
 updateEnemies(dt);updateShots(dt);updateProps(dt);updateTurrets(dt);updateAllies(dt);
 game.enemies=game.enemies.filter(e=>!e.dead);game.shots=game.shots.filter(s=>s.life>0);game.fx=game.fx.filter(f=>(f.life-=dt)>0);game.allies=game.allies.filter(a=>a.hp>0&&a.life>0);
 if(game.boiler.hp<=0||p.hp<=0)finish(false);else if(!game.spawn.length&&!game.enemies.length&&(!game.hulk||game.hulk.hp<=0)&&game.waveClock>2){if(game.wave>=12)finish(true);else showDraft()}
}
function updateEnemies(dt){const p=game.player;for(const e of game.enemies){const d=ENEMIES[e.type];if(e.burn>0){e.burn-=dt;deal(e,6*dt,'Burn',false)}e.slow=Math.max(0,e.slow-dt);e.cd-=dt;let target=p;if(e.type!=='BOSS'&&e.y>620){const t=game.turrets[e.lane];if(t?.hp>0)target=t;else target=game.boiler}const range=d.range||e.r+28,dd=dist(e,target);if(dd>range){const sp=d.speed*(e.slow?0.55:1);e.x+=(target.x-e.x)/dd*sp*dt;e.y+=(target.y-e.y)/dd*sp*dt}else if(e.cd<=0){e.cd=(e.type==='GUNNER'?1.4:.85)*(HEAT[game.heat]?.wind||1);if(e.type==='GUNNER')game.shots.push({x:e.x,y:e.y,vx:(target.x-e.x)/dd*270,vy:(target.y-e.y)/dd*270,damage:d.damage,life:2.2,enemy:true});else hurt(target,d.damage)}if(e.type==='BOSS'&&e.hp<e.maxHp/2&&!e.phase){e.phase=1;e.hp=Math.max(e.hp,e.maxHp*.48);game.fx.push({x:e.x,y:e.y,r:180,life:.8,color:'#ff553c'});toast('THE COLOSSUS TURNS')}}if(game.hulk&&game.hulk.hp>0&&game.waveClock>3&&Math.floor(game.waveClock)%3===0&&rng.next()<dt*.8)spawnEnemy({type:rng.pick(['SWARM','SCRAPPER']),lane:1})}
function updateShots(dt){for(const s of game.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.enemy&&dist(s,game.player)<20){hurt(game.player,s.damage);s.life=0}else if(!s.enemy){const e=nearest(s,game.enemies,22);if(e){deal(e,s.damage,s.source);s.life=0}}}}
function updateProps(dt){for(const p of game.props){if(p.fuse>0&&(p.fuse-=dt)<=0)explode(p);if(p.hp<=0&&p.kind==='crate'){p.kind='debris';game.salvage++;toast('+1 SALVAGE')}}game.props=game.props.filter(p=>p.kind==='vent'||p.kind==='wreck'||p.kind==='debris'||p.hp>0)}
function updateTurrets(dt){for(const t of game.turrets){t.cd-=dt;if(t.hp<=0)continue;const e=nearest(t,game.enemies.filter(e=>e.lane===t.lane),330);if(e&&t.cd<=0){deal(e,11*(1+talent('cannon')*.1),'Deck cannon');game.deckDamage+=11;t.cd=.72;sfx(80)}}}
function updateAllies(dt){for(const a of game.allies){a.life-=dt;a.cd-=dt;const e=nearest(a,game.enemies,220);if(!e)continue;const d=dist(a,e);if(d>35){a.x+=(e.x-a.x)/d*75*dt;a.y+=(e.y-a.y)/d*75*dt}else if(a.cd<=0){deal(e,9,'Crew');a.cd=.8}}}
function nearest(a,list,max=1e9){let out=null,b=max;for(const x of list){const d=dist(a,x);if(d<b){b=d;out=x}}return out}
function hurt(target,amount){if(target===game.player){if(target.inv>0)return;target.inv=.35;if(meta.articles.brace&&keys.has(meta.settings.keys.ability))return}target.hp-=amount;game.fx.push({x:target.x,y:target.y,r:35,life:.25,color:'#ff4c3d'});if(target===game.player&&target.hp<=0&&meta.articles.secondShift&&!game.secondShift){target.hp=1;game.secondShift=true;toast('SECOND SHIFT')}if(target===game.boiler&&target.hp<target.maxHp*.25&&meta.articles.deadman&&!game.deadman){game.deadman=true;blast(game.boiler,220,45,'Deadman')}}
function deal(e,amount,source,fx=true){amount*=1+talent('edge')*.04;e.hp-=amount;game.damage+=amount;if(fx)game.fx.push({x:e.x,y:e.y,r:22,life:.2,color:ELEMENTS[game.skills.find(s=>SHAPES[s.shape]?.name===source)?.element]?.color||'#ffd369'});if(e.hp<=0&&!e.dead){e.dead=true;game.kills++;game.salvage+=rng.next()<.13?1:0;if(meta.articles.pressGang&&rng.next()<.12&&game.allies.length<32)game.allies.push({x:e.x,y:e.y,hp:30,life:25,cd:0});if(dist(e,game.player)<210)game.player.dash=Math.min(2,game.player.dash+1)}}
function blast(at,r,damage,source,element='STEAM'){for(const e of game.enemies)if(!e.dead&&dist(at,e)<r){deal(e,damage,source);applyElement(e,element)}if(game.hulk&&game.hulk.hp>0&&dist(at,game.hulk)<r)game.hulk.hp-=damage;game.fx.push({x:at.x,y:at.y,r,life:.45,color:ELEMENTS[element].color})}
function applyElement(e,el){if(el==='EMBER')e.burn=2;if(el==='FROST')e.slow=2;if(el==='ARC'&&rng.next()<.2)e.cd+=.7;if(el==='STEAM'){const d=Math.hypot(e.x-game.player.x,e.y-game.player.y)||1;e.x+=clamp((e.x-game.player.x)/d*55,-55,55);e.y+=clamp((e.y-game.player.y)/d*55,-55,55)}}
function explode(p){p.hp=0;blast(p,145,78,'Powder keg','EMBER');hurt(game.player,dist(p,game.player)<145?22:0);for(const q of game.props)if(q.kind==='keg'&&q!==p&&dist(p,q)<190&&!q.fuse)q.fuse=.2}

function cast(i){if(mode!=='play')return;const s=game.skills[i],base=SHAPES[s.shape];if(!s||s.cd>0||base.passive)return;s.cd=base.cd*s.mods.cooldown;const aim={x:mouse.x,y:mouse.y},ang=Math.atan2(aim.y-game.player.y,aim.x-game.player.x),range=base.range*s.mods.range*(1+talent('reach')*.05),damage=base.damage*s.mods.damage,candidates=game.enemies.filter(e=>!e.dead);let hit=[];if(['aoe','sentry'].includes(base.kind)){const d=dist(game.player,aim),at=d>range?{x:game.player.x+(aim.x-game.player.x)/d*range,y:game.player.y+(aim.y-game.player.y)/d*range}:aim;if(base.kind==='sentry'){game.allies.push({x:at.x,y:at.y,hp:45,life:14,cd:0});hit=[]}else hit=candidates.filter(e=>dist(e,at)<115)}else if(['line','ray'].includes(base.kind))hit=candidates.filter(e=>{const dx=e.x-game.player.x,dy=e.y-game.player.y,along=dx*Math.cos(ang)+dy*Math.sin(ang),side=Math.abs(-dx*Math.sin(ang)+dy*Math.cos(ang));return along>0&&along<range&&side<(base.kind==='ray'?24:42)});else if(base.kind==='cone')hit=candidates.filter(e=>dist(e,game.player)<range&&Math.abs(angleDiff(Math.atan2(e.y-game.player.y,e.x-game.player.x),ang))<.58);else if(base.kind==='chain'){let e=nearest(aim,candidates,range);for(let j=0;e&&j<3;j++){hit.push(e);e=nearest(e,candidates.filter(x=>!hit.includes(x)),190)}}else hit=candidates.filter(e=>dist(e,game.player)<range);for(const e of hit){deal(e,damage,base.name);applyElement(e,s.element)}if(game.hulk&&dist(aim,game.hulk)<120)game.hulk.hp-=damage;game.fx.push({x:aim.x,y:aim.y,r:base.kind==='aoe'?115:70,life:.35,color:ELEMENTS[s.element].color});sfx(160+i*70)}
const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function dash(){const p=game.player;if(mode!=='play'||p.dash<=0||p.dashCd>0)return;let dx=mouse.x-p.x,dy=mouse.y-p.y,n=Math.hypot(dx,dy)||1;p.x=clamp(p.x+dx/n*170,225,1375);p.y=clamp(p.y+dy/n*170,90,820);p.dash--;p.dashCd=.8;p.inv=.18;blast(p,85,30,'Dash','STEAM');for(const q of game.props)if(q.kind==='keg'&&dist(p,q)<80&&!q.fuse)q.fuse=.45;sfx(90,.12)}
function classAbility(key){const p=game.player;if(game.classId==='captain'&&key===meta.settings.keys.ability&&p.resource>=100){p.resource=0;blast(p,215,40,'Vent');p.hp=Math.min(p.maxHp,p.hp+15);game.healed+=15;game.vents++;toast('PRESSURE VENTED')}else if(game.classId==='boilerwright'&&key===meta.settings.keys.ability&&p.resource>=30){p.resource-=30;blast(p,165,30,'Tap Main','STEAM');game.boiler.hp=Math.min(game.boiler.maxHp,game.boiler.hp+12)}else if(game.classId==='boilerwright'&&key===meta.settings.keys.blowdown&&p.resource>=70){p.resource-=70;blast(p,260,52,'Blowdown','EMBER')}}
function interact(){const broken=nearest(game.player,game.turrets.filter(t=>t.hp<t.maxHp),95);if(broken&&game.salvage>0){game.salvage--;broken.hp=Math.min(broken.maxHp,broken.hp+45);toast('CANNON REPAIRED');return}const crate=nearest(game.player,game.props.filter(p=>p.kind==='crate'),80);if(crate&&meta.berths.includes('winch')){crate.y=clamp(crate.y-150,120,720);toast('CRATE HAULED')}}

function cardOffers(){const out=[];for(let i=0;i<(HEAT[game.heat]?.cards||3);i++){const kind=rng.pick(['new','damage','range','cooldown','element','deck','survival']),name=rng.pick(CARD_NAMES);out.push({name,kind,text:kind==='new'?'Add a new shape × element weapon.':kind==='damage'?'+24% damage to one equipped skill.':kind==='range'?'+20% reach and blast size.':kind==='cooldown'?'−18% cooldown on one skill.':kind==='element'?'Temper one skill with a new element.':kind==='deck'?'Muster crew and repair every cannon.':'Restore 22 hull and Boiler health.'})}return out}
function showDraft(){mode='draft';game.offers=cardOffers();renderDraft()}
function renderDraft(){setScreen(`<div class="panel"><div class="eyebrow">Wave ${game.wave} clear · ${game.rerolls} rerolls</div><h2>CHOOSE WHAT THE STORM MADE OF YOU</h2><div class="cards" id="offers"></div><div class="row" data-actions></div></div>`);const o=$('#offers');game.offers.forEach((c,i)=>{const b=document.createElement('button');b.className='card';b.innerHTML=`<div class="tag">${c.kind.toUpperCase()}</div><h3>${c.name}</h3><p>${c.text}</p><span class="tiny">${i+1} · take card</span>`;b.onclick=()=>pickCard(c);o.append(b)});addButtons([['REROLL',()=>{if(game.rerolls){game.rerolls--;game.offers=cardOffers();renderDraft()} }],['CONTINUE',()=>{},'']]);screen.querySelector('[data-actions] button').disabled=!game.rerolls;screen.querySelector('[data-actions] button:last-child').style.display='none'}
function pickCard(c){const active=game.skills.slice(1),s=rng.pick(active);if(c.kind==='new'){const choices=Object.keys(SHAPES).filter(k=>!game.skills.some(x=>x.shape===k));if(choices.length&&game.skills.length<5)game.skills.push(makeSkill(rng.pick(choices),rng.pick(Object.keys(ELEMENTS))));else s.mods.damage*=1.2}else if(c.kind==='damage')s.mods.damage*=1.24;else if(c.kind==='range')s.mods.range*=1.2;else if(c.kind==='cooldown')s.mods.cooldown*=.82;else if(c.kind==='element')s.element=rng.pick(Object.keys(ELEMENTS));else if(c.kind==='deck'){for(const t of game.turrets)t.hp=t.maxHp;for(let i=0;i<2+talent('crew');i++)game.allies.push({x:800+i*20,y:680,hp:30,life:40,cd:0})}else{game.player.hp=Math.min(game.player.maxHp,game.player.hp+22);game.boiler.hp=Math.min(game.boiler.maxHp,game.boiler.hp+22);game.healed+=22}restow();startWave(game.wave+1);mode='play';setScreen('',false)}
function finish(won){if(game.runDone)return;game.runDone=true;mode='results';const row={date:new Date().toISOString(),seed:game.seed,won,wave:game.wave,classId:game.classId,heat:game.heat,kills:game.kills,damage:Math.round(game.damage),deckDamage:Math.round(game.deckDamage),salvage:game.salvage,vents:Math.round(game.vents),healed:Math.round(game.healed),ship:[...meta.berths]};let gained=0,sigils=0,fitting='';if(meta.unlocked||won){const first=!meta.unlocked;if(first)meta.unlocked=true;gained=game.wave*2+(won?12:0)+Math.round(game.salvage/2);meta.scrip+=gained;const firsts=[];if(won&&!meta.firsts.firstWin)firsts.push('firstWin');if(won&&game.classId==='boilerwright'&&!meta.firsts.boiler)firsts.push('boiler');if(game.wave>=8&&!meta.firsts.eight)firsts.push('eight');for(const f of firsts){meta.firsts[f]=true;sigils++}meta.sigils+=sigils;if(won)meta.bestHeat=Math.max(meta.bestHeat,game.heat);const earn=won&&!meta.fittings.wreck?'wreck':game.wave>=8&&!meta.fittings.barricade?'barricade':won&&game.heat>=1&&!meta.fittings.spareGun?'spareGun':won&&game.classId==='boilerwright'&&!meta.fittings.fourthVent?'fourthVent':game.salvage>=12&&!meta.fittings.winch?'winch':won&&game.healed===0&&!meta.fittings.scupper?'scupper':'';if(earn){meta.fittings[earn]=true;if(meta.berths.length<6)meta.berths.push(earn);fitting=FITTINGS[earn].name}}meta.runs.unshift(row);meta.runs=meta.runs.slice(0,10);save();setScreen(`<div class="panel"><div class="eyebrow">${won?'Run complete':'The deck is lost'}</div><h2>${won?'THE COLOSSUS FALLS':'THE BOILER GOES COLD'}</h2><div class="split"><div><h3>RUN</h3><p>Wave <span class="stat">${game.wave}/12</span><br>Kills <span class="stat">${game.kills}</span><br>Captain damage <span class="stat">${Math.round(game.damage)}</span><br>Deck damage <span class="stat">${Math.round(game.deckDamage)}</span></p></div><div><h3>KEPT</h3><p>Scrip <span class="good">+${gained}</span><br>Sigils <span class="good">+${sigils}</span><br>${fitting?`Fitting <span class="good">${fitting}</span>`:'No new fitting'}</p></div></div><p class="tiny">${game.seed} · ${CLASSES[game.classId].name} · Heat ${game.heat}</p><div class="row" data-actions></div></div>`);addButtons([['SAIL AGAIN',showClass,'primary'],['TITLE',showTitle],...(meta.unlocked?[['WORKSHOP',showWorkshop]]:[])])}

function showWorkshop(){mode='workshop';setScreen(`<div class="panel"><div class="eyebrow">Persistent progression · ${meta.scrip} scrip · ${meta.sigils} sigils</div><h2>THE WORKSHOP</h2><p class="sub">Talents are small, permanent experiments. The draft still decides each run. Respec is free between runs.</p><div class="grid" id="talents"></div><h2>ARTICLES</h2><div class="grid" id="articles"></div><div class="row" data-actions></div></div>`);for(const[id,t]of Object.entries(TALENTS)){const r=talent(id),b=document.createElement('button');b.className='node';b.disabled=r>=t.ranks||meta.scrip<t.cost;b.innerHTML=`<div class="tag">${t.branch} · ${t.cost} SCRIP</div><h3>${t.name} ${r}/${t.ranks}</h3><p>${t.text}</p>`;b.onclick=()=>{meta.scrip-=t.cost;meta.nodes[id]=r+1;save();showWorkshop()};$('#talents').append(b)}for(const[id,a]of Object.entries(ARTICLES)){const owned=!!meta.articles[id],b=document.createElement('button');b.className='node';b.disabled=owned||meta.sigils<a.cost;b.innerHTML=`<div class="tag">ARTICLE · ${a.cost} SIGIL${a.cost>1?'S':''}</div><h3>${a.name}</h3><p>${owned?'OWNED · ':''}${a.text}</p>`;b.onclick=()=>{meta.sigils-=a.cost;meta.spentSigils+=a.cost;meta.articles[id]=true;save();showWorkshop()};$('#articles').append(b)}addButtons([['BACK',showTitle],['RESPEC TALENTS',()=>{for(const[id,r]of Object.entries(meta.nodes))meta.scrip+=TALENTS[id].cost*r;meta.nodes={};save();showWorkshop()}]])}
function showBerths(){mode='berths';setScreen(`<div class="panel"><div class="eyebrow">Ship modifications · ${meta.berths.length}/6 berthed</div><h2>THE BERTHS</h2><p class="sub">Fittings are earned, never bought. They change deck objects or verbs, never player statistics, and remain fixed for an entire run.</p><div class="grid" id="fittings"></div><div class="row" data-actions></div></div>`);for(const[id,f]of Object.entries(FITTINGS)){const owned=!!meta.fittings[id],on=meta.berths.includes(id),b=document.createElement('button');b.className=`node ${owned?'':'locked'}`;b.disabled=!owned;b.innerHTML=`<div class="tag">${on?'BERTHED':owned?'IN STORES':f.rule}</div><h3>${f.name}</h3><p>${f.text}</p>`;b.onclick=()=>{if(on)meta.berths=meta.berths.filter(x=>x!==id);else if(meta.berths.length<6)meta.berths.push(id);save();showBerths()};$('#fittings').append(b)}addButtons([['BACK',showTitle]])}
function showLog(){mode='log';setScreen(`<div class="panel"><div class="eyebrow">Last ten voyages</div><h2>THE RUN LOG</h2><div>${meta.runs.length?meta.runs.map(r=>`<div class="run"><b class="${r.won?'good':'danger'}">${r.won?'VICTORY':'LOST'} · WAVE ${r.wave}</b> · ${r.seed} · ${CLASSES[r.classId]?.name||r.classId} · HEAT ${r.heat}<br><span class="tiny">${r.kills} kills · ${r.damage} captain · ${r.deckDamage} deck · ${(r.ship||[]).length} fittings</span></div>`).join(''):'No voyages recorded.'}</div><div class="row" data-actions></div></div>`);addButtons([['BACK',showTitle]])}
function showSettings(){mode='settings';const k=meta.settings.keys;setScreen(`<div class="panel"><div class="eyebrow">Local settings</div><h2>SETTINGS</h2><div class="grid"><label>VOLUME<br><input id="volume" type="range" min="0" max="1" step=".05" value="${meta.settings.volume}"></label><label><input id="motion" type="checkbox" ${meta.settings.reducedMotion?'checked':''}> REDUCED MOTION</label></div><h3>KEYS</h3><div class="grid" id="binds"></div><div class="row" data-actions></div></div>`);for(const[id,val]of Object.entries(k)){const b=btn(`${id.toUpperCase()} · ${val===' '?'SPACE':val.toUpperCase()}`,()=>{b.textContent=`${id.toUpperCase()} · PRESS A KEY`;const once=e=>{e.preventDefault();meta.settings.keys[id]=e.key.toLowerCase();save();window.removeEventListener('keydown',once,true);showSettings()};window.addEventListener('keydown',once,true)});$('#binds').append(b)}$('#volume').oninput=e=>{meta.settings.volume=+e.target.value;save()};$('#motion').onchange=e=>{meta.settings.reducedMotion=e.target.checked;save()};addButtons([['BACK',()=>{if(game.player&&!game.runDone){mode='play';setScreen('',false);pause()}else showTitle()}],['RESET KEYS',()=>{meta.settings.keys=freshSave().settings.keys;save();showSettings()}]])}
function pause(){if(mode==='play'){mode='pause';setScreen(`<div class="panel"><div class="eyebrow">Simulation stopped</div><h2>PAUSED</h2><div class="row" data-actions></div></div>`);addButtons([['RETURN TO DECK',()=>{mode='play';setScreen('',false)},'primary'],['SETTINGS',showSettings],['ABANDON RUN',()=>finish(false)]])}else if(mode==='pause'){mode='play';setScreen('',false)}}

function draw(){ctx.clearRect(0,0,W,H);drawSky();drawDeck();if(!game.player)return;drawWorld();drawHud()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#243846');g.addColorStop(.5,'#53666c');g.addColorStop(1,'#cf8b58');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.16;ctx.fillStyle='#fff';for(let i=0;i<18;i++){const x=(i*197+(game.time||0)*18)%1800-100,y=80+(i*71)%620;ctx.beginPath();ctx.ellipse(x,y,90,26,0,0,7);ctx.fill()}ctx.globalAlpha=1}
function drawDeck(){ctx.fillStyle='#2a3030';ctx.beginPath();ctx.roundRect(180,40,1240,830,80);ctx.fill();ctx.fillStyle='#806b48';ctx.fillRect(210,70,1180,770);ctx.strokeStyle='#aa9364';ctx.lineWidth=4;for(let y=90;y<840;y+=34){ctx.beginPath();ctx.moveTo(215,y);ctx.lineTo(1385,y);ctx.stroke()}for(const x of[640,960]){ctx.fillStyle='#332b25';ctx.fillRect(x-15,80,30,760)}ctx.fillStyle='#161d20';ctx.fillRect(210,750,1180,90)}
function circle(x,y,r,fill,stroke='#000',lw=2){ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}
function bar(x,y,w,ratio,color){ctx.fillStyle='#080a0b';ctx.fillRect(x,y,w,7);ctx.fillStyle=color;ctx.fillRect(x,y,w*clamp(ratio,0,1),7)}
function drawWorld(){for(const p of game.props){if(p.kind==='debris')continue;if(p.kind==='vent'){circle(p.x,p.y,25,'#213b3d','#66e0d5',3);circle(p.x,p.y,9,'#e6ffff')}else if(p.kind==='keg'){circle(p.x,p.y,22,p.fuse?'#f05b2d':'#633c26','#d8a04b',3)}else if(p.kind==='wreck'){ctx.fillStyle='#4b2723';ctx.fillRect(p.x-65,p.y-35,130,70)}else{ctx.fillStyle='#705033';ctx.fillRect(p.x-28,p.y-28,56,56);bar(p.x-28,p.y-38,56,p.hp/p.maxHp,'#d3aa55')}}for(const t of game.turrets){ctx.fillStyle=t.hp>0?'#7f765d':'#2a2623';ctx.fillRect(t.x-28,t.y-24,56,48);bar(t.x-30,t.y-34,60,t.hp/t.maxHp,'#d6b45e')}circle(game.boiler.x,game.boiler.y,62,'#292d2d','#d9893e',6);circle(game.boiler.x,game.boiler.y,32,'#c34d2d','#ffad5a',4);for(const a of game.allies){circle(a.x,a.y,12,'#c5b873','#f5dc8b');bar(a.x-14,a.y-20,28,a.hp/30,'#5adbc2')}for(const e of game.enemies){const d=ENEMIES[e.type];circle(e.x,e.y,e.r,d.color,e.type==='BOSS'?'#ffce78':'#4a2019',e.type==='BOSS'?6:2);bar(e.x-e.r,e.y-e.r-10,e.r*2,e.hp/e.maxHp,'#e94e3f')}if(game.hulk&&game.hulk.hp>0){ctx.fillStyle='#612e27';ctx.fillRect(game.hulk.x-75,game.hulk.y-30,150,60);bar(game.hulk.x-90,game.hulk.y-44,180,game.hulk.hp/game.hulk.maxHp,'#ff7a42')}for(const s of game.shots)circle(s.x,s.y,5,s.enemy?'#ff563c':'#78dfff');for(const f of game.fx){ctx.globalAlpha=clamp(f.life*2,0,1);ctx.strokeStyle=f.color;ctx.lineWidth=6;ctx.beginPath();ctx.arc(f.x,f.y,f.r*(1-f.life*.35),0,7);ctx.stroke()}ctx.globalAlpha=1;const p=game.player;circle(p.x,p.y,20,game.classId==='captain'?'#2b8f91':'#8b6434','#f7de88',4);ctx.strokeStyle='#fff7c5';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+(mouse.x-p.x)*.12,p.y+(mouse.y-p.y)*.12);ctx.stroke()}
function drawHud(){const p=game.player;ctx.fillStyle='#091116dd';ctx.fillRect(18,18,420,112);ctx.strokeStyle='#a8894e';ctx.strokeRect(18,18,420,112);ctx.fillStyle='#eadba9';ctx.font='700 18px Segoe UI';ctx.fillText(`${CLASSES[game.classId].name} · WAVE ${game.wave}/12 · HEAT ${game.heat}`,34,44);bar(34,57,240,p.hp/p.maxHp,'#cf4e3d');bar(34,76,240,game.boiler.hp/game.boiler.maxHp,'#da9b48');bar(34,95,240,p.resource/100,game.classId==='captain'?'#ff7b38':'#56e5d5');ctx.font='12px Segoe UI';ctx.fillStyle='#ddd';ctx.fillText(`HULL ${Math.ceil(p.hp)}/${p.maxHp}`,286,64);ctx.fillText(`BOILER ${Math.ceil(game.boiler.hp)}/${game.boiler.maxHp}`,286,83);ctx.fillText(`${CLASSES[game.classId].resource} ${Math.floor(p.resource)}%`,286,102);ctx.fillText(`SALVAGE ${game.salvage} · DASH ${p.dash}/2`,34,121);const y=832,w=180,start=410;game.skills.slice(0,5).forEach((s,i)=>{const d=SHAPES[s.shape],e=ELEMENTS[s.element],x=start+i*(w+8);ctx.fillStyle='#0a1116e8';ctx.fillRect(x,y-62,w,52);ctx.strokeStyle=e.color;ctx.strokeRect(x,y-62,w,52);ctx.fillStyle=e.color;ctx.font='700 13px Segoe UI';ctx.fillText(`${i?['LMB','RMB','Q','E'][i-1]:'AUTO'} · ${d.name}`,x+8,y-40);ctx.fillStyle='#bbb';ctx.font='11px Segoe UI';ctx.fillText(`${e.name}${s.cd>0?` · ${s.cd.toFixed(1)}s`:''}`,x+8,y-20)});if(game.eventTimer>0){game.eventTimer-=1/60;ctx.fillStyle='#070b10dd';ctx.fillRect(390,160,820,95);ctx.fillStyle='#f3c76d';ctx.textAlign='center';ctx.font='700 32px Georgia';ctx.fillText(EVENTS[game.event].name,800,198);ctx.fillStyle='#ddd';ctx.font='15px Segoe UI';ctx.fillText(EVENTS[game.event].text,800,228);ctx.textAlign='left'}if(game.blackout){ctx.fillStyle='#0008';ctx.fillRect(0,0,W,H);ctx.globalCompositeOperation='destination-out';const g=ctx.createRadialGradient(p.x,p.y,40,p.x,p.y,260);g.addColorStop(0,'#000');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(p.x-270,p.y-270,540,540);ctx.globalCompositeOperation='source-over'}}

function pointer(e){const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height}
canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',e=>{pointer(e);mouse.down[e.button]=true;if(e.button===0)cast(1);if(e.button===2)cast(2)});canvas.addEventListener('pointerup',e=>mouse.down[e.button]=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(e.key==='Escape'){pause();return}if(mode==='draft'&&['1','2','3'].includes(e.key)){game.offers[+e.key-1]&&pickCard(game.offers[+e.key-1]);return}keys.add(e.key.toLowerCase());if(mode!=='play')return;if(e.key===' ')dash();if(e.key.toLowerCase()==='q')cast(3);if(e.key.toLowerCase()==='e')cast(4);if(e.key.toLowerCase()===meta.settings.keys.interact)interact();classAbility(e.key.toLowerCase())});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
window.__skygear={ELEMENTS,SHAPES,WAVES,HEAT,FITTINGS,TALENTS,ARTICLES,get mode(){return mode},get game(){return game},get meta(){return meta},startRun,finish,resetSave(){localStorage.removeItem(SAVE_KEY);meta=freshSave();showTitle()}};
showTitle();requestAnimationFrame(loop);
