import {ARTICLES,CARDS,ELEMENTS,FITTINGS,HEAT,SHAPES,TALENTS,WAVES,makeSkill,skillName} from './parity-data.js';

export const SAVE_KEY='skygear.browser2d.parity.v2';
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export const hash=text=>{let h=2166136261;for(const c of String(text))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
export class RNG{constructor(seed){this.state=hash(seed)||1}next(){this.state^=this.state<<13;this.state^=this.state>>>17;this.state^=this.state<<5;return(this.state>>>0)/4294967296}int(a,b){return a+Math.floor(this.next()*(b-a+1))}pick(list){return list[Math.floor(this.next()*list.length)]}weighted(rows,weight=x=>x.weight??1){let total=rows.reduce((n,x)=>n+Math.max(0,weight(x)),0),roll=this.next()*total;for(const row of rows){roll-=Math.max(0,weight(row));if(roll<=0)return row}return rows.at(-1)}}

export function freshMeta(){return{version:2,unlocked:false,scrip:0,sigils:0,spentSigils:0,nodes:{},firsts:{},boughtArticles:{},seeds:[],fittings:{},berths:[],heat:0,bestHeat:0,runs:[],settings:{master:.8,music:.55,sfx:.75,voice:.8,reducedMotion:false,hudScale:1,keys:{up:'w',down:'s',left:'a',right:'d',dash:' ',slot1:'1',slot2:'2',slot3:'q',slot4:'e',deckwork:'r',classAbility:'f',secondary:'v',pause:'escape'}}}}
export function mergeMeta(raw){const fresh=freshMeta();if(!raw||typeof raw!=='object')return fresh;return{...fresh,...raw,nodes:{...fresh.nodes,...raw.nodes},firsts:{...fresh.firsts,...raw.firsts},boughtArticles:{...fresh.boughtArticles,...raw.boughtArticles},fittings:{...fresh.fittings,...raw.fittings},settings:{...fresh.settings,...raw.settings,keys:{...fresh.settings.keys,...raw.settings?.keys}},runs:Array.isArray(raw.runs)?raw.runs.slice(-60):[]}}
export function loadMeta(storage=globalThis.localStorage){try{return mergeMeta(JSON.parse(storage.getItem(SAVE_KEY)||'null'))}catch{return freshMeta()}}
export function saveMeta(meta,storage=globalThis.localStorage){try{storage.setItem(SAVE_KEY,JSON.stringify(meta));return true}catch{return false}}

export const talentRank=(meta,id)=>Number(meta.nodes[id]||0);
export function resolvedTalents(meta){const out={};for(const[id,node]of Object.entries(TALENTS)){const rank=talentRank(meta,id);if(rank)out[node.field]=(out[node.field]||0)+node.per*rank}return out}
export function branchBought(meta,branch){return Object.entries(TALENTS).filter(([id,n])=>n.branch===branch&&talentRank(meta,id)>0).length}
export function talentOpen(meta,id){const node=TALENTS[id];return!!node&&branchBought(meta,node.branch)>=node.tier*2}
export function canBuyTalent(meta,id){const n=TALENTS[id];return!!n&&meta.unlocked&&talentOpen(meta,id)&&talentRank(meta,id)<n.ranks&&meta.scrip>=n.cost}
export function buyTalent(meta,id){if(!canBuyTalent(meta,id))return false;meta.scrip-=TALENTS[id].cost;meta.nodes[id]=talentRank(meta,id)+1;return true}
export function respec(meta){for(const[id,rank]of Object.entries(meta.nodes))meta.scrip+=(TALENTS[id]?.cost||0)*rank;meta.nodes={}}
export function articleOwned(meta,id){return!!meta.boughtArticles[id]}
export function canBuyArticle(meta,id){const a=ARTICLES[id];return!!a&&meta.unlocked&&!articleOwned(meta,id)&&(!a.excludes||!articleOwned(meta,a.excludes))&&meta.sigils>=a.cost}
export function buyArticle(meta,id){if(!canBuyArticle(meta,id))return false;meta.sigils-=ARTICLES[id].cost;meta.spentSigils+=ARTICLES[id].cost;meta.boughtArticles[id]=true;return true}
export function liveArticles(meta,classId){const out={};for(const[id,a]of Object.entries(ARTICLES))if(articleOwned(meta,id)&&(!a.captainOnly||classId==='captain'))out[a.field]=true;return out}
export function availableHeat(meta){return meta.unlocked?Math.min(HEAT.length-1,meta.bestHeat+1):0}

export function fittingAward(meta,row){const tests={wreck:()=>row.won,bow_barricade:()=>row.wave>=9,spare_gun:()=>row.won&&row.heat>=1,fourth_vent:()=>row.won&&row.classId==='boilerwright',winch:()=>false,scupper_grating:()=>row.won&&row.healed<=0};for(const id of Object.keys(FITTINGS))if(!FITTINGS[id].tabled&&!meta.fittings[id]&&tests[id]())return id;return''}
export function awardRun(meta,row){const wasLocked=!meta.unlocked;if(wasLocked&&!row.won){meta.runs.push(row);meta.runs=meta.runs.slice(-10);return{scrip:0,sigils:0,fitting:'',firstWin:false}};if(wasLocked)meta.unlocked=true;const seen=meta.seeds.includes(row.seed),scrip=Math.max(0,Math.round((row.wave*4+(row.won?20:0)+row.vents*2+row.closeShare*.25)*(seen?.35:1)));meta.scrip+=scrip;if(!seen)meta.seeds.push(row.seed);const firsts=[];if(row.won&&!meta.firsts.firstWin)firsts.push('firstWin');if(row.won&&row.classId==='boilerwright'&&!meta.firsts.winBoilerwright)firsts.push('winBoilerwright');if(row.wave>=8&&!meta.firsts.reachEight)firsts.push('reachEight');if(row.won&&row.closeShare>=60&&!meta.firsts.wonClose)firsts.push('wonClose');if(row.won&&row.healed<=0&&!meta.firsts.wonUnhealed)firsts.push('wonUnhealed');if(row.won&&row.heat>0&&row.heat<HEAT.length-1&&!meta.firsts[`heat${row.heat}`])firsts.push(`heat${row.heat}`);for(const id of firsts)meta.firsts[id]=true;meta.sigils+=firsts.length;if(row.won)meta.bestHeat=Math.max(meta.bestHeat,row.heat);const fitting=fittingAward(meta,row);if(fitting){meta.fittings[fitting]=true;if(meta.berths.length<6)meta.berths.push(fitting)}meta.runs.push(row);meta.runs=meta.runs.slice(-60);return{scrip,sigils:firsts.length,fitting,firstWin:wasLocked}}

export function freshTelemetry(slots=4){return{per:Array.from({length:Math.max(4,slots)},()=>({casts:0,damage:0,kills:0,hits:0,shape:'',element:''})),basic:{casts:0,damage:0,kills:0,hits:0},deck:{damage:0,kills:0,kegs:0,crates:0,lanterns:0},allies:{damage:0,kills:0},rangeTime:{close:0,mid:0,far:0,none:0},vents:0,healed:0,salvage:0,rerolls:0,taken:0,takenByWave:{}}}
export function noteCast(tel,slot,skill){const bucket=slot<0?tel.basic:tel.per[slot];if(!bucket)return;bucket.casts++;if(slot>=0){bucket.shape=skill.shape;bucket.element=skill.element}}
export function noteDamage(tel,slot,amount,killed=false){const bucket=slot===-3?tel.allies:slot===-2?tel.deck:slot<0?tel.basic:tel.per[slot];if(!bucket)return;bucket.damage+=amount;if('hits'in bucket)bucket.hits++;if(killed)bucket.kills++}
export function noteRange(tel,dt,nearest,close=210){const key=nearest<0?'none':nearest<=close?'close':nearest<=close*2.6?'mid':'far';tel.rangeTime[key]+=dt}
export function slotUse(tel,slot){const damage=tel.per.reduce((n,r)=>n+r.damage,0),casts=tel.per.reduce((n,r)=>n+r.casts,0);const share=damage<200?.25:(tel.per[slot]?.damage||0)/damage,press=casts<12?.25:(tel.per[slot]?.casts||0)/casts;return(share+press)/2}

const ownedElements=run=>[...new Set(run.skills.map(s=>s.element))];
export function cardEligible(card,run){const shapes=run.skills.map(s=>s.shape);switch(card.id){case'aoe':return shapes.some(s=>!['LINE_BURST','CHAIN'].includes(s));case'pierce':return shapes.includes('LINE_BURST');case'jump':return shapes.includes('CHAIN');case'widecone':return run.skills.some(s=>s.shape==='CONE'&&!s.mods.wideCone);case'twin':return run.skills.some(s=>!SHAPES[s.shape].passive&&s.mods.multi<2);case'dashcd':case'dashdmg':case'dashchg':return run.classId==='captain';case'burnDmg':case'burnDur':return ownedElements(run).includes('EMBER');case'slowAmt':case'brittle':return ownedElements(run).includes('FROST');case'stun':return ownedElements(run).includes('ARC');case'knock':case'scald':return ownedElements(run).includes('STEAM');case'spares':return!run.articles.openingBid&&run.rerolls<6;default:return true}}
export function rollCards(run,count){const eligible=CARDS.filter(c=>cardEligible(c,run)),out=[];while(out.length<count&&eligible.length){const card=run.rng.pick(eligible.filter(c=>!out.some(x=>x.id===c.id)));if(!card)break;const offer={...card};if(card.scope==='skill'){const candidates=run.skills.map((s,i)=>({s,i})).filter(({s})=>card.id!=='pierce'||s.shape==='LINE_BURST').filter(({s})=>card.id!=='jump'||s.shape==='CHAIN').filter(({s})=>card.id!=='widecone'||s.shape==='CONE');offer.slot=run.rng.weighted(candidates,({i})=>.25+slotUse(run.telemetry,i)*3)?.i??0;offer.text=`${card.text} on ${skillName(run.skills[offer.slot])}.`}if(card.scope==='element'){offer.element=run.rng.pick(ownedElements(run));offer.title=offer.title.replace('ELEMENT',ELEMENTS[offer.element].name.toUpperCase());offer.text=`${card.text} · ${ELEMENTS[offer.element].name}.`}out.push(offer)}return out}
export function applyCard(run,card){const s=run.skills[card.slot??0],m=run.mods;switch(card.id){case'aoe':s.mods.area*=1.35;break;case'range':s.mods.range*=1.3;break;case'cd':s.mods.cooldown*=.78;break;case'dmg':s.mods.damage*=1.3;break;case'pierce':s.mods.pierce+=2;break;case'jump':s.mods.jumps+=1;break;case'widecone':s.mods.wideCone=true;break;case'knockskill':s.mods.knock*=1.6;break;case'twin':s.mods.multi=2;break;case'reelem':s.element=run.rng.pick(Object.keys(ELEMENTS).filter(e=>e!==s.element));break;case'elemdmg':m.elemDamage[card.element]*=1.3;break;case'elemcd':m.elemCooldown[card.element]*=.8;break;case'burnDmg':m.burnDamage+=.5;break;case'burnDur':m.burnDuration+=2;break;case'slowAmt':m.slowAmount=Math.min(.75,m.slowAmount+.15);break;case'brittle':m.slowDamage+=.25;break;case'stun':m.stunChance+=.15;break;case'knock':m.knockMultiplier+=.4;break;case'scald':m.scald=1;break;case'hp':run.player.maxHp+=20;run.player.hp+=20;break;case'spd':m.moveMultiplier*=1.12;break;case'dashcd':m.dashCooldownBonus+=.25;break;case'dashdmg':m.dashDamage+=60;break;case'dashchg':m.dashCharges++;run.player.maxDashes++;run.player.dashes++;break;case'crit':m.critChance+=.08;break;case'critx':m.critExplode=1;break;case'scrap':m.scrapChance+=.15;break;case'lifesteal':m.lifesteal+=.045;break;case'ventheal':m.ventHeal+=8;break;case'ventdmg':m.ventDamage+=.5;m.ventRadius+=.15;break;case'pressrate':m.pressureRate+=.3;break;case'dressing':m.dressing+=2;break;case'boilerhp':run.boiler.maxHp+=150;run.boiler.hp=Math.min(run.boiler.maxHp,run.boiler.hp+150);break;case'boilerdr':m.boilerDr+=.25;break;case'kegs':m.kegDamage+=.4;m.kegSafe=1;break;case'spares':run.rerolls+=2;break;case'fifth':m.fifthGear=true;break;case'residue':m.residue++;break;case'autofire':m.killAutofire+=.1;break;case'killboom':m.killExplode+=18;break}run.cards.push(card.id)}
export function newMods(){return{elemDamage:{EMBER:1,FROST:1,ARC:1,STEAM:1},elemCooldown:{EMBER:1,FROST:1,ARC:1,STEAM:1},burnDamage:1,burnDuration:2,slowAmount:.25,slowDamage:0,stunChance:.15,knockMultiplier:1,scald:0,moveMultiplier:1,dashCooldownBonus:0,dashDamage:30,dashCharges:2,critChance:.12,critExplode:0,scrapChance:0,lifesteal:0,ventHeal:10,ventDamage:1,ventRadius:1,pressureRate:1,dressing:0,boilerDr:0,kegDamage:1,kegSafe:0,fifthGear:false,residue:0,killAutofire:0,killExplode:0}}
export function waveManifest(n){const wave=WAVES[n-1];if(!wave)return'';const counts={};for(const[,type,count]of wave.batches)counts[type]=(counts[type]||0)+count;return Object.entries(counts).map(([k,v])=>`${v} ${k.toLowerCase()}`).join(' · ')}
export function formatTime(seconds){const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return`${m}:${String(s).padStart(2,'0')}`}
export function reportText(row){return[`SKYGEAR · ${row.won?'DECK HELD':'DECK LOST'}`,`seed ${row.seed} · ${row.classId} · Heat ${row.heat} · ${row.time}`,`wave ${row.wave}/12 · ${row.kills} kills · ${row.salvage} salvage`,`captain ${row.damage} damage · deck ${row.deckDamage} · allies ${row.allyDamage}`,`range ${row.closeShare}% close · ${row.midShare}% mid · ${row.farShare}% far`,`vents ${row.vents} · healed ${row.healed} · taken ${row.taken}`,`cards ${row.cards.join(', ')||'none'}`,`ship ${row.ship.join(', ')||'bare'}`].join('\n')}
export function cloneSkill(shape,element){return makeSkill(shape,element)}
