import {ARTICLES,BUILD,CARDS,CLASSES,ELEMENTS,ENEMIES,EVENTS,FITTINGS,HEAT,SHAPES,TALENTS,WAVES,WORKSHOP_BRANCHES,makeSkill,skillName} from './parity-data.js';
import {RNG,applyCard,articleOwned,availableHeat,awardRun,buyArticle,buyTalent,canBuyArticle,canBuyTalent,clamp,distance,formatTime,freshTelemetry,liveArticles,loadMeta,newMods,noteCast,noteDamage,noteRange,reportText,resolvedTalents,respec,rollCards,saveMeta,talentOpen,talentRank,waveManifest} from './parity-systems.js';

const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),screen=$('#screen'),toastNode=$('#toast');
const W=1600,H=900,LANES=[480,800,1120],WORLD_SPEED=.47,MAX_ALLIES=32;
let meta=loadMeta(),mode='title',run=null,last=0,mouse={x:800,y:320},pressed=new Set(),audioUnlocked=false,menuReturn='title';

class AudioDirector{
 constructor(){this.context=null;this.music=null}
 unlock(){if(audioUnlocked)return;audioUnlocked=true;try{this.context=new AudioContext();this.startMusic()}catch{}}
 tone(freq=220,duration=.06,type='square',volume=.05){if(!this.context||!meta.settings.sfx)return;const o=this.context.createOscillator(),g=this.context.createGain();o.type=type;o.frequency.value=freq;g.gain.value=volume*meta.settings.master*meta.settings.sfx;o.connect(g).connect(this.context.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,this.context.currentTime+duration);o.stop(this.context.currentTime+duration)}
 startMusic(){if(this.music)return;this.music=new Audio('../audio/music/combat_low.mp3');this.music.loop=true;this.music.volume=meta.settings.master*meta.settings.music*.35;this.music.play().catch(()=>{})}
 tier(wave){if(!this.music)return;const file=wave>=12?'boss_loop.mp3':wave>=9?'combat_high.mp3':'combat_low.mp3';if(!this.music.src.endsWith(file)){this.music.src=`../audio/music/${file}`;this.music.play().catch(()=>{})}this.music.volume=meta.settings.master*meta.settings.music*.35}
 voice(kind){const map={wave:'wave_start_1.ogg',clear:'wave_clear_1.ogg',vent:'vent_1.ogg',victory:'victory_1.ogg',defeat:'defeat_1.ogg'};if(!map[kind]||!meta.settings.voice)return;const a=new Audio(`../audio/voice/captain/${map[kind]}`);a.volume=meta.settings.master*meta.settings.voice*.7;a.play().catch(()=>{})}
 sync(){if(this.music)this.music.volume=meta.settings.master*meta.settings.music*.35}
}
const sound=new AudioDirector();
const el=(tag,attrs={},html='')=>{const node=document.createElement(tag);Object.assign(node,attrs);if(html)node.innerHTML=html;return node};
const button=(label,onClick,cls='')=>el('button',{className:cls,onclick:e=>{sound.unlock();sound.tone(520,.035,'square',.025);onClick(e)},textContent:label});
function toast(text){toastNode.textContent=text;toastNode.classList.add('show');clearTimeout(toastNode._timer);toastNode._timer=setTimeout(()=>toastNode.classList.remove('show'),2200)}
function setScreen(html='',active=true){screen.innerHTML=html;screen.classList.toggle('active',active)}
function actions(rows){const host=screen.querySelector('[data-actions]');for(const[label,fn,cls]of rows)host.append(button(label,fn,cls))}
function seedFromUrl(){return new URLSearchParams(location.search).get('seed')||Math.random().toString(36).slice(2,8).toUpperCase()}
function metaSummary(){const wins=meta.runs.filter(r=>r.won),best=meta.runs.reduce((n,r)=>Math.max(n,r.wave||0),0);return`${meta.runs.length} runs · ${wins.length} held · best wave ${best}`}

function showTitle(){mode='title';run=null;const unlocked=meta.unlocked;setScreen(`<div class="panel title-panel"><div class="eyebrow">${BUILD} · top-down browser edition</div><h1>SKYGEAR</h1><p class="sub">Hold three lanes through twelve waves. Build a hand across 36 shape × element combinations. Keep the Boiler lit.</p><div class="hint">WASD move · mouse aim · LMB/RMB/Q/E skills · Space class movement · R deckwork · Esc pause</div><div class="row" data-actions></div><p class="tiny">${metaSummary()} · saves stay in this browser · <span class="stat">?seed=SKY123</span></p></div>`);const rows=[['DEPLOY',showClass,'primary'],['HOW TO PLAY',showHow],...(unlocked?[[`HEAT ${meta.heat} · ${HEAT[meta.heat].name}`,cycleHeat],['WORKSHOP',showWorkshop],['THE BERTHS',showBerths],['RUN LOG',showLog]]:[]),['SETTINGS',()=>showSettings('title')]];actions(rows)}
function cycleHeat(){meta.heat=(meta.heat+1)%(availableHeat(meta)+1);saveMeta(meta);showTitle()}
function showHow(){mode='how';setScreen(`<div class="panel"><div class="eyebrow">The one-page contract</div><h2>HOW TO HOLD THE DECK</h2><div class="split"><div><h3>THE FIGHT</h3><p>Boarders land in three lanes. Each lane cannon holds until it breaks; stand beside a broken gun and hold <span class="kbd">R</span> while carrying salvage to repair it. Kegs chain after a fuse. Crates spill salvage.</p><p>Every fourth wave changes the rules: a grapple, a blackout, then the Colossus.</p></div><div><h3>THE CLASSES</h3><p><b>Captain:</b> fight inside 210 units to build Pressure. It decays at range and vents itself at full.</p><p><b>Boilerwright:</b> stand still on the Boiler, a teal deck vent, or a cracked steam main to bank Head. Banked Head makes every weapon hit 45% harder. Space spends Head on a Bleed Jet; F cracks a main; V blows the bank down.</p></div></div><div class="row" data-actions></div></div>`);actions([['BACK',showTitle]])}
function showClass(){mode='class';setScreen(`<div class="panel"><div class="eyebrow">A real trade, not a skin</div><h2>CHOOSE WHO HOLDS THE DECK</h2><div class="class-compare" id="classes"></div><div class="row" data-actions></div></div>`);for(const[id,c]of Object.entries(CLASSES)){const b=button(c.name,()=>showLoadout(id),'class-card');b.innerHTML=`<div class="tag">${c.gauge} · ${c.hp} HP · ${c.speed} SPEED · ${c.dashes} DASH</div><h3>${c.name}</h3><p>${c.blurb}</p><dl><dt>THE QUESTION</dt><dd>${c.compare.question}</dd><dt>THE GAUGE</dt><dd>${c.compare.gauge}</dd><dt>WHAT IT BUYS</dt><dd>${c.compare.payoff}</dd><dt>YOUR KEYS</dt><dd>${c.compare.keys}</dd><dt>YOU LOSE BY</dt><dd>${c.compare.loss}</dd></dl>`;$('#classes').append(b)}actions([['BACK',showTitle]])}
let loadout={classId:'captain',picks:[]};
function showLoadout(classId=loadout.classId){if(loadout.classId!==classId)loadout={classId,picks:[]};mode='loadout';setScreen(`<div class="panel matrix-panel"><div class="eyebrow">Opening weapons · choose four</div><h2>THE OPEN MATRIX</h2><p class="sub">Your class carries its own automatic attack. Pick four active or passive weapons; every one of the 36 cells executes a distinct shape and element pairing.</p><div class="matrix" id="matrix"><b>SHAPE</b>${Object.values(ELEMENTS).map(e=>`<b style="color:${e.color}">${e.name}</b>`).join('')}</div><div class="row"><span id="pick-count" class="stat"></span></div><div class="row" data-actions></div></div>`);const m=$('#matrix');for(const[shapeId,shape]of Object.entries(SHAPES)){m.insertAdjacentHTML('beforeend',`<b>${shape.name}</b>`);for(const[elementId,element]of Object.entries(ELEMENTS)){const key=`${shapeId}:${elementId}`,b=button(`${shape.name} · ${element.name}`,()=>{const at=loadout.picks.indexOf(key);if(at>=0)loadout.picks.splice(at,1);else if(loadout.picks.length<4)loadout.picks.push(key);showLoadout()});if(loadout.picks.includes(key))b.className='primary';m.append(b)}}$('#pick-count').textContent=`${loadout.picks.length} / 4 chosen`;actions([['BACK',showClass],['SET SAIL',()=>beginRun(classId),loadout.picks.length===4?'primary':'']]);screen.querySelector('[data-actions] button:last-child').disabled=loadout.picks.length!==4}

function beginRun(classId,seed=seedFromUrl()){const c=CLASSES[classId],talents=resolvedTalents(meta),articles=liveArticles(meta,classId),heat=meta.unlocked?meta.heat:0,rng=new RNG(seed);const maxHp=c.hp+(talents.maxHp||0),boilerHp=500+(talents.boilerHp||0),skills=loadout.picks.map(p=>{const[s,e]=p.split(':');return makeSkill(s,e)});if(articles.secondHand)skills.push(makeSkill(rng.pick(['AURA','PULSE']),rng.pick(Object.keys(ELEMENTS))));run={seed,rng,classId,classData:c,talents,articles,heat,heatData:HEAT[heat],state:'play',time:0,wave:0,waveTime:0,event:null,eventTime:0,spawn:[],enemies:[],projectiles:[],props:[],turrets:[],crew:[],sentries:[],fields:[],fx:[],skills,cards:[],mods:newMods(),telemetry:freshTelemetry(skills.length),player:{x:800,y:690,vx:0,vy:0,hp:maxHp,maxHp,speed:c.speed*(1+(talents.moveSpeed||0)),radius:18,invuln:0,gauge:0,maxDashes:c.dashes,dashes:c.dashes,dashClock:0,stationary:0,braceClock:0,recallClock:0},boiler:{x:800,y:785,hp:boilerHp,maxHp:boilerHp,radius:60},rerolls:articles.openingBid?0:(runStartRerolls(heat)+(talents.rerolls||0)),salvage:0,kills:0,damage:0,deckDamage:0,allyDamage:0,healed:0,vents:0,repairHold:0,scuttleUsed:false,secondShiftUsed:false,deadmanUsed:false,basicClock:0,passiveClock:0,coach:new Coach(),finished:false};run.mods.critChance+=(talents.critChance||0);run.mods.dashCharges=c.dashes;restow(true);startWave(1);mode='play';setScreen('',false);sound.tier(1);sound.voice('wave');toast(`${c.name} · ${seed}`)}
const runStartRerolls=heat=>HEAT[heat].startRerolls??2;
function restow(initial=false){const props=[];for(const[x,y]of[[345,270],[615,405],[985,405],[1250,270]])props.push({kind:'crate',x,y,hp:65,maxHp:65,radius:30,dead:false});for(const[x,y]of[[390,570],[690,245],[930,585],[1190,245]])props.push({kind:'keg',x,y,hp:34,maxHp:34,radius:22,fuse:0,dead:false});for(const[x,y]of[[500,690],[800,475],[1100,690]])props.push({kind:'vent',x,y,hp:999,maxHp:999,radius:25,dead:false});if(run.talents.extraKegs)props.push({kind:'keg',x:800+(run.rng.next()-.5)*500,y:330,hp:34,maxHp:34,radius:22,fuse:0,dead:false});const ship=meta.berths.filter(id=>meta.fittings[id]&&!FITTINGS[id].tabled);if(ship.includes('fourth_vent'))props.push({kind:'vent',x:590,y:225,hp:999,maxHp:999,radius:25,dead:false});if(ship.includes('bow_barricade'))for(const x of[745,855])props.push({kind:'crate',x,y:150,hp:65,maxHp:65,radius:30,dead:false});if(ship.includes('wreck'))props.push({kind:'wreck',x:1280,y:105,hp:999,maxHp:999,radius:55,dead:false});if(ship.includes('scupper_grating'))props.push({kind:'vent',x:520,y:600,hp:999,maxHp:999,radius:25,dead:false});run.props=props;if(initial){const max=100*(1+(run.talents.turretHp||0)),scale=run.heatData.turretHpScale??1;run.turrets=LANES.map((x,l)=>({x,y:720,lane:l,hp:max*scale,maxHp:max,cooldown:0,dead:false}));if(ship.includes('spare_gun'))run.turrets.push({x:800,y:640,lane:1,hp:0,maxHp:max,cooldown:0,dead:true,spare:true})}}
function expandBatches(wave){const queue=[];for(const[at,type,count,lane]of wave.batches){if(lane==='all'){for(let i=0;i<count;i++)queue.push({at:at+i*.22,type,lane:i%3})}else for(let i=0;i<count;i++)queue.push({at:at+i*.22,type,lane})}return queue.sort((a,b)=>a.at-b.at)}
function startWave(number){run.wave=number;run.waveTime=0;run.event=WAVES[number-1].event||null;run.eventTime=run.event?2.8:0;run.spawn=expandBatches(WAVES[number-1]);run.scuttleUsed=false;run.deadmanUsed=false;run.player.gauge=Math.max(run.player.gauge,run.talents.wavePressure||0);run.player.hp=Math.min(run.player.maxHp,run.player.hp+(run.talents.waveHeal||0));run.boiler.hp=Math.min(run.boiler.maxHp,run.boiler.hp+(run.talents.boilerRepair||0));restow(false);if(!run.heatData.noMuster){for(let lane=0;lane<3;lane++)for(let i=0;i<2+(run.talents.extraCrew||0);i++)addCrew(lane)}const push=WAVES[number-1].push||(run.heatData.extraPushes||[]).includes(number);run.hulk=push?{x:800,y:65,hp:360+number*25,maxHp:360+number*25,radius:70,cooldown:1.5,dead:false}:null;sound.tier(number);sound.voice('wave');toast(run.event?EVENTS[run.event].name:`WAVE ${number}`)}
function spawnEnemy(spec){const base=ENEMIES[spec.type],hpScale=1+(run.wave-1)*(run.heatData.hpScaling??.06);run.enemies.push({id:run.rng.int(1,1e9),type:spec.type,lane:spec.lane,x:LANES[spec.lane]+(run.rng.next()-.5)*85,y:80,hp:base.hp*hpScale,maxHp:base.hp*hpScale,radius:base.radius,cooldown:.2+run.rng.next(),windup:0,recover:0,slow:0,burn:0,stun:0,phase:0,turning:0,dead:false})}
function addCrew(lane){if(run.crew.length+run.sentries.length>=MAX_ALLIES)return;run.crew.push({kind:'crew',lane,x:LANES[lane]+(run.rng.next()-.5)*55,y:680,hp:42,maxHp:42,cooldown:0,radius:13,dead:false})}

function update(dt){if(mode!=='play'||!run||run.finished)return;run.time+=dt;run.waveTime+=dt;run.eventTime=Math.max(0,run.eventTime-dt);updatePlayer(dt);updateGauge(dt);while(run.spawn.length&&run.spawn[0].at<=run.waveTime)spawnEnemy(run.spawn.shift());updatePassives(dt);updateEnemies(dt);updateProjectiles(dt);updateAllies(dt);updateTurrets(dt);updateProps(dt);updateFields(dt);updateCoach(dt);run.enemies=run.enemies.filter(e=>!e.dead);run.crew=run.crew.filter(a=>!a.dead);run.sentries=run.sentries.filter(a=>!a.dead&&a.life>0);run.projectiles=run.projectiles.filter(p=>p.life>0);run.fields=run.fields.filter(f=>f.life>0);run.fx=run.fx.filter(f=>(f.life-=dt)>0);if(run.player.hp<=0||run.boiler.hp<=0)finishRun(false);else if(!run.spawn.length&&!run.enemies.length&&(!run.hulk||run.hulk.dead)&&run.waveTime>1){if(run.wave===12)finishRun(true);else openDraft()}}
function updatePlayer(dt){const p=run.player,k=meta.settings.keys;p.invuln=Math.max(0,p.invuln-dt);if(p.dashClock>0){p.dashClock=Math.max(0,p.dashClock-dt);if(p.dashClock===0&&p.dashes<p.maxDashes){p.dashes++;if(p.dashes<p.maxDashes)p.dashClock=Math.max(.3,1-run.mods.dashCooldownBonus+(run.talents.dashRecharge||0))}}p.braceClock=Math.max(0,p.braceClock-dt);p.recallClock=Math.max(0,p.recallClock-dt);let dx=(pressed.has(k.right)?1:0)-(pressed.has(k.left)?1:0),dy=(pressed.has(k.down)?1:0)-(pressed.has(k.up)?1:0),mag=Math.hypot(dx,dy)||1,speed=p.speed*run.mods.moveMultiplier;p.vx+=(dx/mag*speed-p.vx)*Math.min(1,dt*13);p.vy+=(dy/mag*speed-p.vy)*Math.min(1,dt*13);p.x=clamp(p.x+p.vx*dt,225,1375);p.y=clamp(p.y+p.vy*dt,90,820);if(Math.hypot(p.vx,p.vy)<12)p.stationary+=dt;else p.stationary=0;run.basicClock-=dt;if(run.basicClock<=0){const target=nearest(p,run.enemies,run.classData.auto.range);if(target){basicAttack(target);run.basicClock=run.classData.auto.period}}if(pressed.has(k.deckwork))deckwork(dt);else run.repairHold=0}
function updateGauge(dt){const p=run.player,c=run.classData;if(run.classId==='captain'){const near=nearest(p,run.enemies,210);if(!near)p.gauge=Math.max(0,p.gauge-dt*12);if(p.gauge>=100)ventCaptain()}else if(p.stationary>.18){let rate=0;if(distance(p,run.boiler)<100)rate=c.boilerRate;for(const prop of run.props)if(prop.kind==='vent'&&!prop.dead&&distance(p,prop)<72)rate=Math.max(rate,c.ventRate);for(const field of run.fields)if(field.kind==='main'&&distance(p,field)<field.radius)rate=Math.max(rate,c.tapRate);if(rate)p.gauge=clamp(p.gauge+rate*dt*(1+(run.talents.pressureRate||0)),0,100)}}
function basicAttack(target){const c=run.classData.auto,p=run.player,angle=Math.atan2(target.y-p.y,target.x-p.x),hits=run.enemies.filter(e=>distance(p,e)<=c.range&&Math.abs(angleDiff(Math.atan2(e.y-p.y,e.x-p.x),angle))<=c.arc/2);noteCast(run.telemetry,-1,{shape:'AUTO',element:c.element});for(const e of hits)damageEnemy(e,c.damage,-1,c.element,c.knock);run.fx.push({kind:'arc',x:p.x,y:p.y,r:c.range*.5,color:ELEMENTS[c.element].color,life:.22});sound.tone(135,.05,'sawtooth',.04)}
function updatePassives(dt){run.passiveClock-=dt;if(run.passiveClock>0)return;run.passiveClock=.45;run.skills.forEach((s,i)=>{const shape=SHAPES[s.shape];if(s.shape==='AURA'){for(const e of run.enemies)if(distance(e,run.player)<shape.radius*s.mods.area)damageEnemy(e,shape.damage/shape.tickRate,i,s.element,shape.knock||0);noteCast(run.telemetry,i,s)}else if(s.shape==='PULSE'&&s.cooldown<=0){blast(run.player,shape.radius*s.mods.area,shape.damage*s.mods.damage,i,s.element,shape.knock);s.cooldown=shape.cooldown;noteCast(run.telemetry,i,s)}s.cooldown=Math.max(0,s.cooldown-.45)})}
function updateEnemies(dt){for(const e of run.enemies){const d=ENEMIES[e.type];if(e.turning>0){e.turning-=dt;continue}if(e.burn>0){e.burn-=dt;damageEnemy(e,(6*run.mods.burnDamage)*dt,-4,'EMBER',0,false)}e.slow=Math.max(0,e.slow-dt);e.stun=Math.max(0,e.stun-dt);e.cooldown-=dt;if(e.stun>0)continue;const target=enemyTarget(e),reach=d.ai==='ranged'?d.attackRange:(d.reach||d.attackRange)+target.radius,range=reach*WORLD_SPEED+.5*target.radius,away=distance(e,target);if(e.windup>0){e.windup-=dt;if(e.windup<=0){enemyStrike(e,target,d);e.recover=d.recover}continue}if(e.recover>0){e.recover-=dt;continue}if(away>range){const speed=d.speed*WORLD_SPEED*(e.slow?1-run.mods.slowAmount:1);e.x+=(target.x-e.x)/away*speed*dt;e.y+=(target.y-e.y)/away*speed*dt}else if(e.cooldown<=0){e.windup=d.windup*(run.heatData.windup||1);e.cooldown=e.windup+d.recover+.15}if(e.type==='BOSS'&&e.hp<e.maxHp*.5&&!e.phase){e.phase=1;e.turning=1.4;e.hp=Math.max(e.hp,e.maxHp*.48);run.fx.push({kind:'ring',x:e.x,y:e.y,r:230,color:'#ff4d37',life:1.4});toast('THE COLOSSUS TURNS')}if(e.type==='BOSS'&&e.phase&&e.cooldown<.1&&run.rng.next()<dt*.45)bossSlam(e)}if(run.hulk&&!run.hulk.dead){run.hulk.cooldown-=dt;if(run.hulk.cooldown<=0){spawnEnemy({type:run.rng.pick(['SWARM','SCRAPPER']),lane:1});run.hulk.cooldown=2.4}}}
function enemyTarget(e){const turret=run.turrets.find(t=>t.lane===e.lane&&!t.dead);if(turret&&e.y>570)return turret;if(e.lane===1||e.type==='BOSS')return distance(e,run.player)<200?run.player:run.boiler;return distance(e,run.player)<210?run.player:(turret||run.boiler)}
function enemyStrike(e,target,d){if(d.ai==='ranged'){const len=distance(e,target)||1;run.projectiles.push({x:e.x,y:e.y,vx:(target.x-e.x)/len*d.boltSpeed*WORLD_SPEED,vy:(target.y-e.y)/len*d.boltSpeed*WORLD_SPEED,damage:d.damage,enemy:true,life:4,radius:7,trail:[]})}else hurtTarget(target,d.damage);sound.tone(e.type==='BOSS'?55:88,.08,'square',.035)}
function bossSlam(e){run.fx.push({kind:'telegraph',x:e.x,y:e.y,r:e.phase?220:150,color:'#ff503c',life:.65,damageAt:.05});setTimeout(()=>{if(run&&mode==='play'&&distance(e,run.player)<(e.phase?220:150))hurtTarget(run.player,26)},600)}
function updateProjectiles(dt){for(const p of run.projectiles){p.trail.push({x:p.x,y:p.y});if(p.trail.length>9)p.trail.shift();p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.enemy&&distance(p,run.player)<p.radius+run.player.radius){hurtTarget(run.player,p.damage);p.life=0}else if(!p.enemy){const e=nearest(p,run.enemies,p.radius+20);if(e){damageEnemy(e,p.damage,p.slot,p.element,p.knock);p.life=0}}}}
function updateAllies(dt){for(const a of[...run.crew,...run.sentries]){if(a.kind==='sentry')a.life-=dt;a.cooldown-=dt;const enemy=nearest(a,run.enemies,a.kind==='sentry'?420:260);if(!enemy)continue;const gap=distance(a,enemy);if(a.kind==='crew'&&gap>35){a.x+=(enemy.x-a.x)/gap*75*dt;a.y+=(enemy.y-a.y)/gap*75*dt}else if(a.cooldown<=0){const dmg=a.kind==='sentry'?14:9;damageEnemy(enemy,dmg,-3,a.element||'EMBER',a.kind==='sentry'?70:20);run.allyDamage+=dmg;a.cooldown=a.kind==='sentry'?1/1.4:.8}}}
function updateTurrets(dt){for(const t of run.turrets){t.cooldown-=dt;if(t.dead)continue;const e=nearest(t,run.enemies.filter(x=>x.lane===t.lane),360);if(e&&t.cooldown<=0){damageEnemy(e,11,-2,'EMBER',35);run.deckDamage+=11;t.cooldown=.72/(1+(run.talents.turretRate||0));sound.tone(72,.08,'square',.04)}}}
function updateProps(dt){for(const p of run.props){if(p.fuse>0&&(p.fuse-=dt)<=0)explodeKeg(p);if(p.hp<=0&&!p.dead){p.dead=true;if(p.kind==='crate'){run.salvage+=run.talents.blackoutCrate?2:1;run.telemetry.salvage+=run.talents.blackoutCrate?2:1;run.telemetry.deck.crates++;healPlayer(6+(run.talents.salvageHeal||0));toast('+1 SALVAGE')}}}}
function updateFields(dt){for(const f of run.fields){f.life-=dt;f.tick-=dt;if(f.tick<=0){f.tick=.25;for(const e of run.enemies)if(distance(f,e)<f.radius)damageEnemy(e,f.dps*.25,f.slot??-4,f.element||'EMBER',0)}}}
function updateCoach(dt){const nearestEnemy=nearest(run.player,run.enemies,1e9),close=nearestEnemy?distance(run.player,nearestEnemy):-1;noteRange(run.telemetry,dt,close);run.coach.update(dt,close)}

function nearest(at,list,max=1e9){let best=null,gap=max;for(const item of list){if(item.dead)continue;const d=distance(at,item);if(d<gap){best=item;gap=d}}return best}
const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function hurtTarget(target,amount){if(target===run.player){if(target.invuln>0||target.braceClock>0)return;target.invuln=.42;run.telemetry.taken+=amount;run.telemetry.takenByWave[run.wave]=(run.telemetry.takenByWave[run.wave]||0)+amount}if(target===run.boiler)amount*=1-run.mods.boilerDr;target.hp-=amount;run.fx.push({kind:'hit',x:target.x,y:target.y,r:35,color:'#ff503c',life:.28});if(target===run.player&&target.hp<=0&&run.articles.secondShift&&!run.secondShiftUsed){run.secondShiftUsed=true;target.hp=1;toast('SECOND SHIFT')}if(target===run.boiler&&target.hp<target.maxHp*.25&&run.articles.deadmansSwitch&&!run.deadmanUsed){run.deadmanUsed=true;blast(run.boiler,220,40,-2,'STEAM',300)}}
function damageEnemy(e,amount,slot,element='EMBER',knock=0,visual=true){if(e.dead)return;const before=e.hp;let actual=amount*run.mods.elemDamage[element];if(run.classId==='boilerwright'&&run.player.gauge>0)actual*=1+run.classData.overpressure;if(e.slow>0)actual*=1+run.mods.slowDamage;const crit=run.rng.next()<run.mods.critChance;if(crit)actual*=2;e.hp-=actual;run.damage+=slot>=-1?actual:0;const killed=e.hp<=0;noteDamage(run.telemetry,slot,actual,killed);if(element==='EMBER'){e.burn=run.mods.burnDuration}else if(element==='FROST'){e.slow=2}else if(element==='ARC'&&run.rng.next()<run.mods.stunChance)e.stun=.7;else if(element==='STEAM'&&run.mods.scald)e.burn=run.mods.burnDuration;if(knock){const d=distance(run.player,e)||1,travel=Math.min(390,knock*run.mods.knockMultiplier*(e.type==='BOSS'?.12:.24));e.x=clamp(e.x+(e.x-run.player.x)/d*travel,230,1370);e.y=clamp(e.y+(e.y-run.player.y)/d*travel,75,735)}if(visual)run.fx.push({kind:crit?'crit':'hit',x:e.x,y:e.y,r:crit?42:24,color:ELEMENTS[element].color,life:.24});if(run.classId==='captain'&&distance(run.player,e)<=210){run.player.gauge=clamp(run.player.gauge+actual*.16*run.mods.pressureRate*(run.event==='blackout'?1.45:1),0,100);if(run.mods.lifesteal)healPlayer(actual*run.mods.lifesteal)}if(killed)killEnemy(e,slot,element);return Math.min(before,actual)}
function killEnemy(e,slot,element){e.dead=true;run.kills++;if(run.rng.next()<.12)run.salvage++;if(run.rng.next()<run.mods.scrapChance)healPlayer(12);if(run.mods.killExplode)blast(e,90,run.mods.killExplode,slot,element,0);if(run.articles.pressGang&&distance(run.player,e)<210&&run.rng.next()<.16)addCrew(e.lane);if(run.mods.killAutofire&&run.rng.next()<run.mods.killAutofire)castSkill(0,nearest(run.player,run.enemies,1e9));if(run.classId==='captain')run.player.dashes=Math.min(run.player.maxDashes,run.player.dashes+1)}
function healPlayer(amount){const before=run.player.hp;run.player.hp=Math.min(run.player.maxHp,run.player.hp+amount);const gained=run.player.hp-before;run.healed+=gained;run.telemetry.healed+=gained}
function blast(at,radius,damage,slot,element,knock=0){for(const e of run.enemies)if(distance(at,e)<=radius)damageEnemy(e,damage,slot,element,knock);if(run.hulk&&!run.hulk.dead&&distance(at,run.hulk)<=radius){run.hulk.hp-=damage;if(run.hulk.hp<=0){run.hulk.dead=true;toast('BOARDING HULK BROKEN')}}run.fx.push({kind:'ring',x:at.x,y:at.y,r:radius,color:ELEMENTS[element].color,life:.5})}
function ventCaptain(){const heal=run.mods.ventHeal+(run.talents.ventHeal||0),radius=215*run.mods.ventRadius*(1+(run.talents.ventRadius||0));run.player.gauge=0;blast(run.player,radius,40*run.mods.ventDamage,-1,'STEAM',340);healPlayer(heal);run.vents++;run.telemetry.vents++;sound.voice('vent');toast('PRESSURE VENTS ITSELF')}
function blowdown(){if(run.classId!=='boilerwright'||run.player.gauge<=0)return;const bank=run.player.gauge,damage=25+bank*.65;run.player.gauge=0;blast(run.player,170+bank*1.15,damage,-1,'STEAM',260);run.boiler.hp=Math.min(run.boiler.maxHp,run.boiler.hp+bank*.18);run.vents++;run.telemetry.vents++;sound.voice('vent');toast(`BLOWDOWN · ${Math.round(bank)} HEAD`)}
function classMovement(){if(run.classId==='captain')dash();else bleedJet()}
function dash(){const p=run.player;if(p.dashes<=0||p.dashClock>0)return;const d=distance(p,mouse)||1,from={x:p.x,y:p.y};p.x=clamp(p.x+(mouse.x-p.x)/d*220,225,1375);p.y=clamp(p.y+(mouse.y-p.y)/d*220,90,820);p.dashes--;p.dashClock=Math.max(.3,1-run.mods.dashCooldownBonus+(run.talents.dashRecharge||0));p.invuln=.18;for(const e of run.enemies)if(segmentDistance(e,from,p)<e.radius+26){damageEnemy(e,run.mods.dashDamage,-1,'STEAM',130);if(run.articles.keelHauling){e.x+=(p.x-from.x)*.35;e.y+=(p.y-from.y)*.35}}for(const prop of run.props)if(prop.kind==='keg'&&distance(prop,p)<85&&!prop.fuse)prop.fuse=.45;sound.tone(82,.12,'sawtooth',.05)}
function bleedJet(){const p=run.player,c=run.classData;if(p.gauge<c.jet.cost)return;const d=distance(p,mouse)||1,from={x:p.x,y:p.y};p.gauge-=c.jet.cost;p.x=clamp(p.x+(mouse.x-p.x)/d*c.jet.distance,225,1375);p.y=clamp(p.y+(mouse.y-p.y)/d*c.jet.distance,90,820);p.invuln=.16;for(let i=0;i<c.jet.trail;i++){const u=i/(c.jet.trail-1);run.fields.push({kind:'scald',x:from.x+(p.x-from.x)*u,y:from.y+(p.y-from.y)*u,radius:c.jet.trailRadius,dps:c.jet.trailDps,life:c.jet.trailLife,tick:0,element:'STEAM',slot:-1})}sound.tone(100,.14,'sawtooth',.05)}
function segmentDistance(p,a,b){const l2=(b.x-a.x)**2+(b.y-a.y)**2;if(!l2)return distance(p,a);const t=clamp(((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/l2,0,1);return distance(p,{x:a.x+t*(b.x-a.x),y:a.y+t*(b.y-a.y)})}

function castSkill(index,forcedTarget=null){if(mode!=='play'||!run)return;const s=run.skills[index],shape=SHAPES[s?.shape];if(!s||shape.passive||s.cooldown>0)return;const target=forcedTarget||mouse,p=run.player,range=(shape.deployRange||shape.range||shape.radius)*s.mods.range*(1+(run.talents.range||0)),d=distance(p,target)||1,aim=d>range?{x:p.x+(target.x-p.x)/d*range,y:p.y+(target.y-p.y)/d*range}:target;let fifth=run.mods.fifthGear&&((s.casts+1)%5===0),damage=shape.damage*s.mods.damage*(fifth?2:1),casts=s.mods.multi;noteCast(run.telemetry,index,s);s.casts++;if(!fifth)s.cooldown=shape.cooldown*s.mods.cooldown*run.mods.elemCooldown[s.element];for(let cast=0;cast<casts;cast++){const scale=casts>1?.7:1;if(shape.kind==='sentry'){if(run.sentries.length<shape.maxLive&&run.crew.length+run.sentries.length<MAX_ALLIES)run.sentries.push({kind:'sentry',x:aim.x,y:aim.y,hp:55,maxHp:55,radius:15,cooldown:0,life:shape.life,element:s.element,dead:false})}else{const hits=skillHits(shape,s,aim);for(const e of hits)damageEnemy(e,damage*scale,index,s.element,shape.knock*s.mods.knock);if(run.hulk&&!run.hulk.dead&&distance(aim,run.hulk)<130){run.hulk.hp-=damage*scale;if(run.hulk.hp<=0)run.hulk.dead=true}}}if(run.mods.residue)run.fields.push({kind:'residue',x:aim.x,y:aim.y,radius:75,dps:8,life:2*run.mods.residue,tick:0,element:'EMBER',slot:index});run.fx.push({kind:'cast',x:aim.x,y:aim.y,r:shape.radius||70,color:ELEMENTS[s.element].color,life:.35});sound.tone(170+index*65,.08,index%2?'triangle':'sawtooth',.045)}
function skillHits(shape,skill,aim){const p=run.player,range=(shape.range||shape.radius)*skill.mods.range*(1+(run.talents.range||0)),angle=Math.atan2(aim.y-p.y,aim.x-p.x),list=run.enemies.filter(e=>!e.dead);if(shape.kind==='aoe')return list.filter(e=>distance(e,aim)<=shape.radius*skill.mods.area);if(shape.kind==='line'||shape.kind==='ray')return list.filter(e=>{const dx=e.x-p.x,dy=e.y-p.y,along=dx*Math.cos(angle)+dy*Math.sin(angle),side=Math.abs(-dx*Math.sin(angle)+dy*Math.cos(angle));return along>=0&&along<=range&&side<((shape.width||26)*skill.mods.area+e.radius)}).slice(0,1+skill.mods.pierce);if(shape.kind==='cone')return list.filter(e=>distance(e,p)<=range&&Math.abs(angleDiff(Math.atan2(e.y-p.y,e.x-p.x),angle))<((skill.mods.wideCone?1.658:shape.arc)/2));if(shape.kind==='chain'){const out=[];let next=nearest(aim,list,range);for(let i=0;next&&i<shape.jumps+skill.mods.jumps;i++){out.push(next);next=nearest(next,list.filter(e=>!out.includes(e)),shape.jumpRange)}return out}return list.filter(e=>distance(e,p)<=range)}
function deckwork(dt){const broken=nearest(run.player,run.turrets.filter(t=>t.dead),95);if(!broken||run.salvage<=0){run.repairHold=0;return}run.repairHold+=dt;if(run.repairHold>=1){run.repairHold=0;run.salvage--;broken.hp=broken.maxHp*.55;broken.dead=false;toast('CANNON REPAIRED');sound.tone(420,.16,'square',.05)}}
function classAbility(){if(run.classId==='boilerwright'){run.fields.push({kind:'main',x:run.player.x,y:run.player.y,radius:95,dps:6,life:8,tick:0,element:'STEAM',slot:-1});toast('STEAM MAIN CRACKED')}else if(run.articles.brace&&run.player.braceClock<=0){run.player.braceClock=.35;toast('BRACED')}else if(run.articles.recall&&run.player.recallClock<=0){run.player.x=run.boiler.x;run.player.y=run.boiler.y-90;run.player.recallClock=45;toast('RECALLED')}}
function secondaryAbility(){if(run.classId==='boilerwright')blowdown();else if(run.articles.scuttle&&!run.scuttleUsed){run.scuttleUsed=true;for(const p of run.props)if(p.kind==='keg'&&!p.dead)p.fuse=.15;toast('SCUTTLE')}}
function explodeKeg(p){if(p.dead)return;p.dead=true;run.telemetry.deck.kegs++;const damage=78*run.mods.kegDamage;blast(p,175,damage,-2,'EMBER',220);if(!run.mods.kegSafe&&distance(p,run.player)<175)hurtTarget(run.player,22);for(const q of run.props)if(q.kind==='keg'&&!q.dead&&!q.fuse&&distance(p,q)<200)q.fuse=.2}

function openDraft(){mode='draft';run.state='draft';sound.voice('clear');const count=Math.min(run.heatData.draftOffers??4,run.wave===1&&run.talents.fourthCard?4:3);run.offers=rollCards(run,count);renderDraft()}
function renderDraft(){const manifest=run.talents.showManifest?`<div class="hint">NEXT · ${waveManifest(run.wave+1)}</div>`:'';setScreen(`<div class="panel"><div class="eyebrow">Wave ${run.wave} clear · ${run.rerolls} rerolls</div><h2>CHOOSE WHAT THE STORM MADE OF YOU</h2>${manifest}<div class="cards" id="offers"></div><div class="row" data-actions></div></div>`);run.offers.forEach((card,i)=>{const b=button(card.title,()=>takeCard(card),'card');b.innerHTML=`<div class="tag ${card.rarity}">${card.rarity.toUpperCase()} · ${card.scope.toUpperCase()}</div><h3>${card.title}</h3><p>${card.text}</p><span class="tiny">${i+1} · take card</span>`;$('#offers').append(b)});actions([['REROLL',rerollDraft]]);screen.querySelector('[data-actions] button').disabled=!run.rerolls||run.articles.openingBid}
function rerollDraft(){if(run.rerolls<=0||run.articles.openingBid)return;run.rerolls--;run.telemetry.rerolls++;run.offers=rollCards(run,run.heatData.draftOffers??3);renderDraft()}
function takeCard(card){applyCard(run,card);startWave(run.wave+1);run.state='play';mode='play';setScreen('',false)}

function finishRun(won){if(run.finished)return;run.finished=true;mode='results';const rt=run.telemetry.rangeTime,total=rt.close+rt.mid+rt.far||1,row={date:new Date().toISOString(),build:BUILD,seed:run.seed,won,wave:run.wave,classId:run.classId,heat:run.heat,time:formatTime(run.time),seconds:Math.round(run.time),kills:run.kills,damage:Math.round(run.damage),deckDamage:Math.round(run.deckDamage),allyDamage:Math.round(run.allyDamage),salvage:run.salvage,vents:run.vents,healed:Math.round(run.healed),taken:Math.round(run.telemetry.taken),closeShare:Math.round(rt.close/total*100),midShare:Math.round(rt.mid/total*100),farShare:Math.round(rt.far/total*100),cards:[...run.cards],ship:meta.berths.filter(id=>meta.fittings[id]&&!FITTINGS[id].tabled),skills:run.skills.map(skillName),per:run.telemetry.per};row.report=reportText(row);const bank=awardRun(meta,row);saveMeta(meta);sound.voice(won?'victory':'defeat');setScreen(`<div class="panel"><div class="eyebrow">${won?'Deck held':'Deck lost'} · ${row.seed}</div><h2>${won?'THE COLOSSUS FALLS':'THE BOILER GOES COLD'}</h2><div class="split"><div><h3>RUN</h3><p>Wave <span class="stat">${row.wave}/12</span><br>Time <span class="stat">${row.time}</span><br>Kills <span class="stat">${row.kills}</span><br>Captain <span class="stat">${row.damage}</span> · Deck <span class="stat">${row.deckDamage}</span> · Allies <span class="stat">${row.allyDamage}</span></p><p>Range: ${row.closeShare}% close · ${row.midShare}% mid · ${row.farShare}% far</p></div><div><h3>KEPT</h3><p>Scrip <span class="good">+${bank.scrip}</span><br>Sigils <span class="good">+${bank.sigils}</span><br>${bank.fitting?`Fitting <span class="good">${FITTINGS[bank.fitting].name}</span>`:'No new fitting'}</p></div></div><pre id="report">${row.report}</pre><div class="row" data-actions></div></div>`);actions([['COPY REPORT',()=>navigator.clipboard?.writeText(row.report).then(()=>toast('REPORT COPIED')).catch(()=>toast('COPY REFUSED'))],['SAIL AGAIN',showClass,'primary'],['TITLE',showTitle],...(meta.unlocked?[['WORKSHOP',showWorkshop]]:[])])}

function showWorkshop(){mode='workshop';setScreen(`<div class="panel wide-panel"><div class="eyebrow">${meta.scrip} scrip · ${meta.sigils} sigils</div><h2>THE WORKSHOP</h2><p class="sub">Talents stay below three draft cards at full purchase. Tier 1 opens after two nodes in a branch; Tier 2 after four. Respec is free between runs.</p><div id="branches"></div><h2>THE ARTICLES</h2><p class="sub">Sigils come only from firsts. Articles are permanent commitments; exclusions are enforced.</p><div class="grid" id="articles"></div><div class="row" data-actions></div></div>`);for(const[branch,label]of Object.entries(WORKSHOP_BRANCHES)){const section=el('section',{className:'workshop-branch'},`<h3>${label}</h3><div class="grid"></div>`),grid=section.querySelector('.grid');for(const[id,n]of Object.entries(TALENTS).filter(([,x])=>x.branch===branch)){const rank=talentRank(meta,id),open=talentOpen(meta,id),b=button(n.name,()=>{if(buyTalent(meta,id)){saveMeta(meta);showWorkshop()}},`node ${open?'':'locked'}`);b.disabled=!canBuyTalent(meta,id);b.innerHTML=`<div class="tag">TIER ${n.tier} · ${n.cost} SCRIP</div><h3>${n.name} ${rank}/${n.ranks}</h3><p>${n.text}</p>${open?'':'<span class="tiny">BUY TWO NODES PER PRIOR TIER</span>'}`;grid.append(b)}$('#branches').append(section)}for(const[id,a]of Object.entries(ARTICLES)){const owned=articleOwned(meta,id),blocked=a.excludes&&articleOwned(meta,a.excludes),b=button(a.name,()=>{if(buyArticle(meta,id)){saveMeta(meta);showWorkshop()}},'node');b.disabled=!canBuyArticle(meta,id);b.innerHTML=`<div class="tag">${a.cost} SIGIL${a.cost===1?'':'S'}${a.captainOnly?' · CAPTAIN':''}</div><h3>${a.name}</h3><p>${a.text}</p><span class="tiny">${owned?'SIGNED':blocked?'EXCLUDED':'AVAILABLE'}</span>`;$('#articles').append(b)}actions([['BACK',showTitle],['RESPEC TALENTS',()=>{respec(meta);saveMeta(meta);showWorkshop()}]])}
function showBerths(){mode='berths';setScreen(`<div class="panel"><div class="eyebrow">${meta.berths.length}/6 berthed · fixed for the whole run</div><h2>THE BERTHS</h2><p class="sub">Fittings are earned rather than bought and change the deck or its verbs, never captain statistics.</p><div class="grid" id="fittings"></div><div class="row" data-actions></div></div>`);for(const[id,f]of Object.entries(FITTINGS)){const owned=!!meta.fittings[id],on=meta.berths.includes(id),b=button(f.name,()=>{if(!owned||f.tabled)return;if(on)meta.berths=meta.berths.filter(x=>x!==id);else if(meta.berths.length<6)meta.berths.push(id);saveMeta(meta);showBerths()},`node ${owned?'':'locked'}`);b.disabled=!owned||f.tabled;b.innerHTML=`<div class="tag">${f.tabled?'TABLED':on?'BERTHED':owned?'IN STORES':f.earn.toUpperCase()}</div><h3>${f.name}</h3><p>${f.text}</p>`;$('#fittings').append(b)}actions([['BACK',showTitle]])}
function showLog(){mode='log';const rows=[...meta.runs].reverse();setScreen(`<div class="panel wide-panel"><div class="eyebrow">${metaSummary()} · keeps 60 voyages</div><h2>THE RUN LOG</h2><div id="runs">${rows.length?'':'No voyages recorded.'}</div><div class="row" data-actions></div></div>`);for(const row of rows){const d=el('details',{className:'run'},`<summary><b class="${row.won?'good':'danger'}">${row.won?'HELD':'LOST'} · WAVE ${row.wave}</b> · ${row.seed} · ${CLASSES[row.classId]?.name||row.classId} · HEAT ${row.heat} · ${row.time}</summary><pre>${row.report||reportText(row)}</pre>`);$('#runs').append(d)}actions([['BACK',showTitle],['CLEAR LOG',()=>{meta.runs=[];saveMeta(meta);showLog()}]])}
function showSettings(back=mode){menuReturn=back;mode='settings';const k=meta.settings.keys;setScreen(`<div class="panel"><div class="eyebrow">Per-bus audio · local controls</div><h2>SETTINGS</h2><div class="settings-grid"><label>MASTER <input data-volume="master" type="range" min="0" max="1" step=".05" value="${meta.settings.master}"></label><label>MUSIC <input data-volume="music" type="range" min="0" max="1" step=".05" value="${meta.settings.music}"></label><label>SFX <input data-volume="sfx" type="range" min="0" max="1" step=".05" value="${meta.settings.sfx}"></label><label>VOICE <input data-volume="voice" type="range" min="0" max="1" step=".05" value="${meta.settings.voice}"></label><label>HUD SCALE <input id="hud-scale" type="range" min=".8" max="1.35" step=".05" value="${meta.settings.hudScale}"></label><label><input id="reduced" type="checkbox" ${meta.settings.reducedMotion?'checked':''}> REDUCED MOTION</label></div><h3>KEYS</h3><div class="grid" id="binds"></div><div class="row" data-actions></div></div>`);for(const[id,key]of Object.entries(k)){const b=button(`${id.toUpperCase()} · ${key===' '?'SPACE':key.toUpperCase()}`,()=>captureBind(id,b));$('#binds').append(b)}for(const input of screen.querySelectorAll('[data-volume]'))input.oninput=e=>{meta.settings[e.target.dataset.volume]=+e.target.value;sound.sync();saveMeta(meta)};$('#hud-scale').oninput=e=>{meta.settings.hudScale=+e.target.value;saveMeta(meta)};$('#reduced').onchange=e=>{meta.settings.reducedMotion=e.target.checked;saveMeta(meta)};actions([['BACK',returnFromSettings],['RESET KEYS',()=>{meta.settings.keys={up:'w',down:'s',left:'a',right:'d',dash:' ',slot1:'1',slot2:'2',slot3:'q',slot4:'e',deckwork:'r',classAbility:'f',secondary:'v',pause:'escape'};saveMeta(meta);showSettings(menuReturn)}]])}
function captureBind(id,b){b.textContent=`${id.toUpperCase()} · PRESS A KEY`;const listener=e=>{e.preventDefault();meta.settings.keys[id]=e.key.toLowerCase();saveMeta(meta);window.removeEventListener('keydown',listener,true);showSettings(menuReturn)};window.addEventListener('keydown',listener,true)}
function returnFromSettings(){if(menuReturn==='pause'&&run){mode='play';pause()}else showTitle()}
function pause(){if(mode==='play'){mode='pause';setScreen(`<div class="panel"><div class="eyebrow">Simulation stopped</div><h2>PAUSED</h2><div class="row" data-actions></div></div>`);actions([['RETURN TO DECK',()=>{mode='play';setScreen('',false)},'primary'],['SETTINGS',()=>showSettings('pause')],['ABANDON RUN',()=>finishRun(false)]])}else if(mode==='pause'){mode='play';setScreen('',false)}}

class Coach{
 constructor(){this.dwell={};this.shown={};this.last={};this.current='';this.until=0;this.foundVent=false}
 update(dt,nearestDistance){if(run.wave<2)return;const onVent=run.classId==='boilerwright'&&run.props.some(p=>p.kind==='vent'&&!p.dead&&distance(p,run.player)<72);if(onVent)this.foundVent=true;const broken=run.turrets.some(t=>t.dead),conditions={broken:broken&&run.salvage>0,findVent:run.classId==='boilerwright'&&!this.foundVent,empty:run.classId==='boilerwright'&&run.player.gauge<=0&&nearestDistance>=0&&nearestDistance<700,kiting:run.classId==='captain'&&nearestDistance>336,gauge:run.classId==='captain'&&run.player.gauge>98&&nearestDistance>0&&nearestDistance<460,idle:run.skills.some((s,i)=>!SHAPES[s.shape].passive&&run.telemetry.per[i].casts===0)};const order=[['broken',3.5,`A cannon is down. Stand at it and HOLD ${keyLabel('deckwork')} to bring it back.`],['findVent',6,`Those steaming teal grates are vents — HEAD for free while you stand on one.`],['empty',7,'Head is empty, so every weapon is hitting soft. Stand on a vent or crack a main with F.'],['gauge',8,'Gauge is full. Get among them: it vents by itself and heals you.'],['kiting',11,'You have been at range a while — Pressure only fills inside 210 units.'],['idle',9,'You have a weapon you have never fired. Q and E are drafted too.']];for(const[id,need,text]of order){this.dwell[id]=conditions[id]?(this.dwell[id]||0)+dt:0;if(this.dwell[id]>=need&&(this.shown[id]||0)<2&&run.time-(this.last[id]||-999)>42&&run.time>this.until){this.current=text;this.until=run.time+4.5;this.shown[id]=(this.shown[id]||0)+1;this.last[id]=run.time;this.dwell[id]=0;break}}if(run.time>this.until)this.current=''}
}
const keyLabel=id=>meta.settings.keys[id]===' '?'SPACE':meta.settings.keys[id].toUpperCase();

function draw(){ctx.clearRect(0,0,W,H);drawSky();drawDeck();if(!run)return;drawWorld();drawHud()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#203746');g.addColorStop(.52,'#52666b');g.addColorStop(1,'#d38d58');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const drift=(run?.time||0)*22;ctx.globalAlpha=.18;ctx.fillStyle='#fff';for(let i=0;i<19;i++){const x=(i*197+drift)%1850-130,y=70+(i*73)%650;ctx.beginPath();ctx.ellipse(x,y,95,28,0,0,7);ctx.fill()}ctx.globalAlpha=1}
function drawDeck(){ctx.fillStyle='#222b2d';ctx.beginPath();ctx.roundRect(175,38,1250,835,80);ctx.fill();ctx.fillStyle='#806d49';ctx.fillRect(210,68,1180,770);ctx.strokeStyle='#ad9568';ctx.lineWidth=3;for(let y=86;y<840;y+=34){ctx.beginPath();ctx.moveTo(214,y);ctx.lineTo(1386,y);ctx.stroke()}for(const x of[640,960]){ctx.fillStyle='#352d27';ctx.fillRect(x-15,78,30,760)}ctx.fillStyle='#151d20';ctx.fillRect(210,742,1180,98)}
function circle(x,y,r,fill,stroke='#000',width=2){ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}
function bar(x,y,w,ratio,color,height=7){ctx.fillStyle='#080a0b';ctx.fillRect(x,y,w,height);ctx.fillStyle=color;ctx.fillRect(x,y,w*clamp(ratio,0,1),height)}
function drawWorld(){for(const p of run.props){if(p.dead)continue;if(p.kind==='vent'){circle(p.x,p.y,27,'#203c3e','#63e1d5',4);circle(p.x,p.y,9,'#d7ffff');if(run.classId==='boilerwright'){ctx.strokeStyle='#44cfca88';ctx.beginPath();ctx.arc(p.x,p.y,70,0,7);ctx.stroke()}}else if(p.kind==='keg'){circle(p.x,p.y,22,p.fuse?'#f05b2d':'#633c26','#d8a04b',3)}else if(p.kind==='wreck'){ctx.fillStyle='#4b2723';ctx.fillRect(p.x-68,p.y-36,136,72)}else{ctx.fillStyle='#705033';ctx.fillRect(p.x-29,p.y-29,58,58);bar(p.x-29,p.y-39,58,p.hp/p.maxHp,'#d3aa55')}}for(const t of run.turrets){ctx.fillStyle=t.dead?'#292522':'#817760';ctx.fillRect(t.x-30,t.y-24,60,48);bar(t.x-31,t.y-35,62,t.hp/t.maxHp,t.dead?'#663a32':'#d8b65e')}circle(run.boiler.x,run.boiler.y,62,'#292d2d','#d9893e',6);circle(run.boiler.x,run.boiler.y,32,'#c34d2d','#ffad5a',4);for(const f of run.fields){ctx.globalAlpha=.22;circle(f.x,f.y,f.radius,ELEMENTS[f.element||'STEAM'].color,'transparent',0);ctx.globalAlpha=1}for(const a of[...run.crew,...run.sentries]){circle(a.x,a.y,a.kind==='sentry'?16:13,a.kind==='sentry'?'#5c7480':'#c5b873','#f5dc8b');bar(a.x-15,a.y-22,30,a.hp/a.maxHp,'#5adbc2')}for(const e of run.enemies){const d=ENEMIES[e.type];if(e.windup>0){ctx.globalAlpha=.45;ctx.strokeStyle='#ff533d';ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,(d.reach||d.attackRange)*WORLD_SPEED,0,7);ctx.stroke();ctx.globalAlpha=1}circle(e.x,e.y,e.radius,d.color,e.type==='BOSS'?'#ffce78':'#4a2019',e.type==='BOSS'?6:2);bar(e.x-e.radius,e.y-e.radius-11,e.radius*2,e.hp/e.maxHp,'#e94e3f');if(run.talents.showNumbers){ctx.fillStyle='#fff';ctx.font='11px Segoe UI';ctx.textAlign='center';ctx.fillText(`${Math.ceil(e.hp)}/${Math.ceil(e.maxHp)}`,e.x,e.y-e.radius-15);ctx.textAlign='left'}}if(run.hulk&&!run.hulk.dead){ctx.fillStyle='#612e27';ctx.fillRect(run.hulk.x-76,run.hulk.y-30,152,60);bar(run.hulk.x-90,run.hulk.y-45,180,run.hulk.hp/run.hulk.maxHp,'#ff7a42',10);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText('BOARDING HULK',run.hulk.x,run.hulk.y-51);ctx.textAlign='left'}for(const p of run.projectiles){ctx.strokeStyle='#ffb0a0';ctx.beginPath();for(let i=0;i<p.trail.length;i++){const q=p.trail[i];if(i===0)ctx.moveTo(q.x,q.y);else ctx.lineTo(q.x,q.y)}ctx.stroke();circle(p.x,p.y,p.radius,p.enemy?'#ff553c':ELEMENTS[p.element].color)}for(const f of run.fx){ctx.globalAlpha=clamp(f.life*2,0,1);ctx.strokeStyle=f.color;ctx.lineWidth=f.kind==='crit'?9:5;ctx.beginPath();ctx.arc(f.x,f.y,f.r||f.radius||30,0,7);ctx.stroke()}ctx.globalAlpha=1;const p=run.player;circle(p.x,p.y,p.radius,run.classId==='captain'?'#278f91':'#8b6434','#f7de88',4);ctx.strokeStyle='#fff7c5';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+(mouse.x-p.x)*.14,p.y+(mouse.y-p.y)*.14);ctx.stroke()}
function drawHud(){const scale=meta.settings.hudScale;ctx.save();ctx.scale(scale,scale);const p=run.player;ctx.fillStyle='#091116e8';ctx.fillRect(18,18,440,120);ctx.strokeStyle='#a8894e';ctx.strokeRect(18,18,440,120);ctx.fillStyle='#eadba9';ctx.font='700 18px Segoe UI';ctx.fillText(`${run.classData.name} · WAVE ${run.wave}/12 · HEAT ${run.heat}`,34,44);bar(34,57,250,p.hp/p.maxHp,'#cf4e3d');bar(34,77,250,run.boiler.hp/run.boiler.maxHp,'#da9b48');bar(34,97,250,p.gauge/100,run.classId==='captain'?'#ff7b38':'#56e5d5');ctx.font='12px Segoe UI';ctx.fillStyle='#ddd';ctx.fillText(`HULL ${Math.ceil(p.hp)}/${p.maxHp}`,294,64);ctx.fillText(`BOILER ${Math.ceil(run.boiler.hp)}/${run.boiler.maxHp}`,294,84);ctx.fillText(`${run.classData.gauge} ${Math.floor(p.gauge)}%`,294,104);ctx.fillText(`SALVAGE ${run.salvage} · ${run.classId==='captain'?`DASH ${p.dashes}/${p.maxDashes}`:'SPACE · BLEED JET'}`,34,124);ctx.restore();const keys=['LMB','RMB',keyLabel('slot3'),keyLabel('slot4'),'AUTO'],slotW=174,start=350,y=840;run.skills.forEach((s,i)=>{const shape=SHAPES[s.shape],element=ELEMENTS[s.element],x=start+i*(slotW+8);ctx.fillStyle='#091116e8';ctx.fillRect(x,y-58,slotW,50);ctx.strokeStyle=element.color;ctx.strokeRect(x,y-58,slotW,50);ctx.fillStyle=element.color;ctx.font='700 13px Segoe UI';ctx.fillText(`${keys[i]||'AUTO'} · ${shape.name}`,x+8,y-37);ctx.fillStyle='#bbb';ctx.font='11px Segoe UI';ctx.fillText(`${element.name}${s.cooldown>0?` · ${s.cooldown.toFixed(1)}s`:''}`,x+8,y-19)});if(run.coach.current){ctx.fillStyle='#071015e8';ctx.fillRect(350,690,900,48);ctx.strokeStyle='#d0a657';ctx.strokeRect(350,690,900,48);ctx.fillStyle='#f0deb0';ctx.textAlign='center';ctx.font='700 15px Segoe UI';ctx.fillText(run.coach.current,800,720);ctx.textAlign='left'}if(run.eventTime>0&&run.event){const event=EVENTS[run.event];ctx.fillStyle='#050910df';ctx.fillRect(350,155,900,110);ctx.fillStyle=event.tint;ctx.textAlign='center';ctx.font='700 34px Georgia';ctx.fillText(event.name,800,200);ctx.fillStyle='#ddd';ctx.font='15px Segoe UI';ctx.fillText(event.blurb,800,232);ctx.textAlign='left'}if(run.event==='blackout'){ctx.fillStyle='#000b';ctx.fillRect(0,0,W,H);ctx.globalCompositeOperation='destination-out';const g=ctx.createRadialGradient(p.x,p.y,35,p.x,p.y,250);g.addColorStop(0,'#000');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(p.x-260,p.y-260,520,520);ctx.globalCompositeOperation='source-over'}if(run.talents.showQueue){ctx.fillStyle='#091116dd';ctx.fillRect(1190,18,390,52);ctx.fillStyle='#ddd';ctx.font='12px Segoe UI';ctx.fillText(`STILL COMING · ${run.spawn.length} · ALIVE ${run.enemies.length}`,1210,48)}}

function pointer(e){const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height}
canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',e=>{sound.unlock();pointer(e);if(e.button===0)castSkill(0);if(e.button===2)castSkill(1)});canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase(),k=meta.settings.keys;if(key===k.pause){e.preventDefault();pause();return}if(mode==='draft'&&['1','2','3','4'].includes(key)){run.offers[+key-1]&&takeCard(run.offers[+key-1]);return}pressed.add(key);if(mode!=='play')return;if(key===k.dash){e.preventDefault();classMovement()}if(key===k.slot1)castSkill(0);if(key===k.slot2)castSkill(1);if(key===k.slot3)castSkill(2);if(key===k.slot4)castSkill(3);if(key===k.classAbility)classAbility();if(key===k.secondary)secondaryAbility()});window.addEventListener('keyup',e=>pressed.delete(e.key.toLowerCase()));
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}

window.__skygearParity={BUILD,ELEMENTS,SHAPES,WAVES,CARDS,TALENTS,ARTICLES,FITTINGS,HEAT,CLASSES,get mode(){return mode},get run(){return run},get meta(){return meta},resetSave(){localStorage.removeItem('skygear.browser2d.parity.v2');meta=loadMeta();showTitle()},debug:{finishWave(){if(!run)return;run.spawn=[];for(const e of run.enemies)e.dead=true;if(run.hulk)run.hulk.dead=true},finishRun(win=true){if(run)finishRun(win)},grantMeta(){meta.unlocked=true;meta.scrip=9999;meta.sigils=99;meta.bestHeat=5;for(const id of Object.keys(FITTINGS))if(!FITTINGS[id].tabled)meta.fittings[id]=true;saveMeta(meta)}}};
showTitle();requestAnimationFrame(loop);
