import {ARTICLES,CLASSES,ELEMENTS,HEAT,SHAPES,TALENTS,WAVES,makeSkill} from './parity-data.js';
import {awardRun,buyArticle,buyTalent,canBuyArticle,canBuyTalent,freshMeta,loadMeta,saveMeta,talentRank} from './parity-systems.js';

const G=window.SKYGEAR,S=G.S,cv=document.getElementById('c');
const ui={mode:'title',classId:'captain',picks:[],meta:loadMeta(),head:0,boosted:false,awarded:false};
const OPENING_SKILLS=[['RANGED_AOE','FROST'],['CONE','EMBER'],['LINE_BURST','ARC']];
const overlay=document.createElement('canvas');overlay.id='v1-parity-ui';Object.assign(overlay.style,{position:'fixed',inset:'0',width:'100vw',height:'100vh',pointerEvents:'auto',zIndex:'10'});document.body.append(overlay);const oc=overlay.getContext('2d');
const fit=()=>{const d=Math.min(devicePixelRatio||1,2);overlay.width=innerWidth*d;overlay.height=innerHeight*d;oc.setTransform(d,0,0,d,0,0)};addEventListener('resize',fit);fit();
const touchTarget=matchMedia('(pointer:coarse)').matches||innerWidth<760||new URLSearchParams(location.search).has('mobile-preview');
const mobile=document.createElement('div');mobile.id='v1-mobile-controls';Object.assign(mobile.style,{position:'fixed',inset:'0',zIndex:'20',pointerEvents:'none',display:touchTarget?'block':'none',fontFamily:'Trebuchet MS,system-ui,sans-serif'});mobile.innerHTML=`<div class="v1-stick" aria-label="Move"><span></span></div><div class="v1-auto">SMART CAST · NEAREST</div><div class="v1-actions"><button data-key="1">1</button><button data-key="2">2</button><button data-key="3">3</button><button data-key="4">4</button><button data-key="e" class="dash">DASH</button></div>`;
document.body.append(mobile);
const mobileStyle=document.createElement('style');mobileStyle.textContent=`#v1-mobile-controls .v1-stick{position:absolute;left:3vw;bottom:14vh;width:min(29vw,144px);height:min(29vw,144px);border:2px solid rgba(240,200,120,.58);border-radius:50%;background:rgba(20,15,12,.46);pointer-events:auto;touch-action:none;box-shadow:0 4px 18px rgba(0,0,0,.28)}#v1-mobile-controls .v1-stick span{position:absolute;left:35%;top:35%;width:30%;height:30%;border-radius:50%;background:rgba(240,200,120,.82);box-shadow:0 0 16px rgba(240,200,120,.34)}#v1-mobile-controls .v1-auto{position:absolute;left:3vw;bottom:calc(14vh + min(29vw,144px) + 10px);padding:5px 8px;border:1px solid rgba(127,199,217,.55);border-radius:7px;background:rgba(20,15,12,.72);color:#7fc7d9;font:800 10px Trebuchet MS,system-ui,sans-serif;letter-spacing:.08em;pointer-events:none}#v1-mobile-controls .v1-actions{position:absolute;right:3vw;bottom:14vh;width:min(60vw,250px);display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px;pointer-events:auto;touch-action:none}#v1-mobile-controls button{width:48px;height:48px;border:2px solid #d4a648;border-radius:50%;background:rgba(36,25,17,.94);color:#f0c878;font:900 16px Trebuchet MS,system-ui,sans-serif;touch-action:none;box-shadow:0 3px 12px rgba(0,0,0,.3)}#v1-mobile-controls button.dash{width:72px;border-radius:10px;font-size:10px;color:#7fc7d9}`;document.head.append(mobileStyle);
const mobileInput=G.Input;mobileInput.mobileMode=touchTarget;
function setMobileKey(k,on){if(!mobileInput)return;if(on){if(!mobileInput.keys.has(k))mobileInput.pressed.add(k);mobileInput.keys.add(k)}else mobileInput.keys.delete(k)}
function clearStick(){for(const k of ['w','a','s','d'])setMobileKey(k,false)}
function aimAt(x,y){window.dispatchEvent(new MouseEvent('mousemove',{clientX:x,clientY:y,bubbles:true}))}
const stick=mobile.querySelector('.v1-stick'),knob=stick.querySelector('span');let stickId=null;function moveStick(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,len=Math.hypot(dx,dy),m=r.width*.34,k=Math.min(1,len/m);knob.style.transform=`translate(${dx?dx/len*m*k:0}px,${dy?dy/len*m*k:0}px)`;clearStick();if(k>.18){if(Math.abs(dx)>Math.abs(dy))setMobileKey(dx<0?'a':'d',true);else setMobileKey(dy<0?'w':'s',true)}}stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(stickId);moveStick(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)moveStick(e)});stick.addEventListener('pointerup',e=>{if(e.pointerId===stickId){stickId=null;clearStick();knob.style.transform=''}});stick.addEventListener('pointercancel',()=>{stickId=null;clearStick();knob.style.transform=''})
for(const b of mobile.querySelectorAll('button')){const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);setMobileKey(k,true)});const release=e=>{e.preventDefault();setMobileKey(k,false)};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release)}
function updateMobileVisibility(){mobile.style.display=touchTarget&&ui.mode==='play'?'block':'none'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function setMode(m){ui.mode=m;overlay.style.pointerEvents=m==='play'?'none':'auto';S.mode=m==='play'?'play':m==='title'?'title':'parity-'+m}
function text(t,x,y,size=16,color='#F0C878',align='center',weight=700){oc.font=`${weight} ${size}px Trebuchet MS,system-ui,sans-serif`;oc.textAlign=align;oc.textBaseline='middle';oc.fillStyle=color;oc.fillText(t,x,y)}
function panel(x,y,w,h,alpha=.92){oc.save();oc.fillStyle=`rgba(23,16,12,${alpha})`;oc.strokeStyle='#D4A648';oc.lineWidth=3;oc.beginPath();oc.roundRect(x,y,w,h,12);oc.fill();oc.stroke();oc.strokeStyle='rgba(255,220,130,.28)';oc.lineWidth=1;oc.strokeRect(x+7,y+7,w-14,h-14);oc.restore()}
function title(t,y,size=32){text(t,innerWidth/2,y,size,'#F0C878','center',900)}
function currentClass(){return CLASSES[ui.classId]}
function installData(){
  Object.assign(G.SHAPES,{AURA:{key:'AURA',noun:'Field',kind:'aura',desc:'persistent field around the captain',radius:150,tickRate:1.8,dmg:4,cd:1.8,knock:25,passive:true},PULSE:{key:'PULSE',noun:'Pulse',kind:'pulse',desc:'automatic radial pressure burst',radius:210,castRange:260,dmg:34,cd:4.4,knock:220,passive:true},SENTRY:{key:'SENTRY',noun:'Sentry',kind:'sentry',desc:'deployable deck sentry',range:420,deployRange:520,dmg:14,cd:9,life:14,fireRate:1.4,autoAfter:2.5,maxLive:2,knock:70}});
  const converted=WAVES.map((w,i)=>({boss:i===11,event:w.event||'',push:!!w.push,batches:(w.batches||[]).map(b=>b.slice()),loop:i===11?{every:9.5,sets:[['SWARM',5],['SCRAPPER',4],['GUNNER',3]]}:undefined}));
  G.WAVES.splice(0,G.WAVES.length,...converted);
  // Godot's opening hand is three weapon cards, not a full build editor. Keep the V1 draft renderer for every later wave, but widen NEW SKILL to all nine shapes.
  const salvage=G.CARDS.find(c=>c.id==='newskill');
  if(salvage)salvage.make=(state)=>{const empty=[];for(let i=0;i<state.unlockedSlots;i++)if(!state.slots[i])empty.push(i);const i=empty[0];if(i===undefined)return null;const held=state.slots.filter(Boolean).map(sk=>sk.shape);const shapes=Object.keys(SHAPES).filter(shape=>!held.includes(shape));const shape=shapes.length?shapes[Math.floor(Math.random()*shapes.length)]:Object.keys(SHAPES)[Math.floor(Math.random()*Object.keys(SHAPES).length)];const element=Object.keys(ELEMENTS)[Math.floor(Math.random()*Object.keys(ELEMENTS).length)];const sk=G.newSkill(shape,element);return{title:'SALVAGED GEAR',text:'Slot '+(i+1)+': '+skillLabel(sk)+' - '+SHAPES[shape].desc+', '+ELEMENTS[element].blurb+'.',slot:i,apply:S=>{S.slots[i]=sk}}};
}
function resetOverlay(){ui.classId='captain';ui.picks=[];ui.head=0;ui.boosted=false;ui.awarded=false;setMode('title')}
function chosen(key){return ui.picks.includes(key)}
function skillLabel(sk){return (ELEMENTS[sk.element]?.name||sk.element)+' '+(SHAPES[sk.shape]?.name||SHAPES[sk.shape]?.noun||sk.shape)}
function launch(){
  const c=currentClass(),t=ui.meta.nodes||{};
  G.TUNING.player.hp=c.hp+(talentRank(ui.meta,'padded_coat')*8||0);G.TUNING.player.speed=c.speed;G.TUNING.player.dashCharges=c.dashes;
  G.startRun();S.classId=ui.classId;S.className=c.name;S.classData=c;
  // The fixed class weapon is the Godot basic attack. The opening draft adds exactly one ability; later V1 drafts fill slots 3 and 4 as they unlock.
  const basic=ui.classId==='boilerwright'?['CONE','STEAM']:['CLOSEHIT','EMBER'];
  const picked=ui.picks[0]||OPENING_SKILLS[0].join(':');
  const[a,b]=picked.split(':');
  S.slots=[G.newSkill(basic[0],basic[1]),G.newSkill(a,b),null,null];
  S.unlockedSlots=2;S.head=0;S.mods.dashCharges=c.dashes;S.player.dashStock=c.dashes;S.player.maxHp=c.hp;S.player.hp=c.hp;setMode('play');
}
function drawClass(){
  const compact=innerWidth<600, short=innerHeight<560;
  if(short&&!compact){
    panel(innerWidth*.05,innerHeight*.08,innerWidth*.90,innerHeight*.80);
    text('CHOOSE WHO HOLDS THE DECK',innerWidth/2,innerHeight*.14,11,'#7FC7D9','center',800);
    title('THE ARTICLES OF COMMAND',innerHeight*.24,28);
    const cards=[['captain',.07],['boilerwright',.51]], y=innerHeight*.36, w=innerWidth*.42, h=innerHeight*.32;
    cards.forEach(([id,xr])=>{const c=CLASSES[id],x=innerWidth*xr;panel(x,y,w,h,.88);text(c.gauge+' - '+c.hp+' HP - '+c.speed+' SPEED',x+w/2,y+18,9,'#7FC7D9');text(c.name,x+w/2,y+43,16,'#F0C878','center',900);text(c.blurb,x+w/2,y+70,8,'#DCD2B4');text(c.compare.question,x+w/2,y+94,8,'#C9BC96');text(c.compare.payoff,x+w/2,y+114,8,'#C9BC96')});
    text('TAP A CAPTAIN',innerWidth/2,innerHeight*.93,11,'#FFD36B','center',800);return;
  }
  if(compact){
    panel(innerWidth*.04,innerHeight*.04,innerWidth*.92,innerHeight*.92);text('CHOOSE WHO HOLDS THE DECK',innerWidth/2,innerHeight*.10,12,'#7FC7D9','center',800);title('THE ARTICLES OF COMMAND',innerHeight*.16,21);
    const cards=[['captain',.18],['boilerwright',.52]],x=innerWidth*.08,w=innerWidth*.84,h=innerHeight*.25;
    cards.forEach(([id],i)=>{const c=CLASSES[id],y=innerHeight*(.23+i*.30);panel(x,y,w,h,.88);text(c.gauge+'  -  '+c.hp+' HP  -  '+c.speed+' SPEED',x+w/2,y+22,10,'#7FC7D9');text(c.name,x+w/2,y+52,19,'#F0C878','center',900);text(c.blurb,x+w/2,y+82,9,'#DCD2B4');text(c.compare.question,x+w/2,y+116,9,'#C9BC96');text(c.compare.payoff,x+w/2,y+148,9,'#C9BC96')});
    text('TAP A CAPTAIN',innerWidth/2,innerHeight*.90,13,'#FFD36B','center',800);return;
  }
  panel(innerWidth*.10,innerHeight*.18,innerWidth*.80,innerHeight*.64);text('CHOOSE WHO HOLDS THE DECK',innerWidth/2,innerHeight*.25,15,'#7FC7D9','center',800);title('THE ARTICLES OF COMMAND',innerHeight*.32,44);
  const cards=[['captain',.18],['boilerwright',.52]];cards.forEach(([id,xr])=>{const c=CLASSES[id],x=innerWidth*xr,y=innerHeight*.39,w=innerWidth*.30,h=innerHeight*.27;panel(x,y,w,h,.88);text(c.gauge+'  -  '+c.hp+' HP  -  '+c.speed+' SPEED',x+w/2,y+28,13,'#7FC7D9');text(c.name,x+w/2,y+66,25,'#F0C878','center',900);text(c.blurb,x+w/2,y+106,14,'#DCD2B4');text(c.compare.question,x+w/2,y+142,13,'#C9BC96');text(c.compare.payoff,x+w/2,y+174,12,'#C9BC96')});text('CLICK A CAPTAIN',innerWidth/2,innerHeight*.75,16,'#FFD36B','center',800);
}function drawLoadout(){
  const compact=innerWidth<600, short=innerHeight<560;
  if(short&&!compact){
    panel(innerWidth*.04,innerHeight*.08,innerWidth*.92,innerHeight*.78);text('OPENING WEAPONS - CHOOSE ONE',innerWidth/2,innerHeight*.15,11,'#7FC7D9');title('THE OPENING DRAFT',innerHeight*.24,29);text('Class weapon aboard; new skills arrive between waves.',innerWidth/2,innerHeight*.30,10,'#C9BC96');
    const w=innerWidth*.27,h=innerHeight*.34,gap=innerWidth*.03,x0=(innerWidth-(w*3+gap*2))/2,y=innerHeight*.37;OPENING_SKILLS.forEach(([shape,element],i)=>{const x=x0+i*(w+gap),sd=SHAPES[shape],ed=ELEMENTS[element],active=chosen(shape+':'+element);panel(x,y,w,h,active?.92:.86);oc.strokeStyle=ed.color;oc.lineWidth=active?3:1;oc.strokeRect(x+6,y+6,w-12,h-12);text('WEAPON '+(i+1),x+w/2,y+19,9,'#7FC7D9');text(ed.name.toUpperCase(),x+w/2,y+49,15,ed.color,'center',900);text(sd.name.toUpperCase(),x+w/2,y+79,17,'#F0C878','center',900);text((sd.kind||'ability').toUpperCase()+' weapon',x+w/2,y+105,9,'#C9BC96');text(active?'SELECTED':'CHOOSE',x+w/2,y+h-14,9,active?'#FFD36B':'#8A7B5C','center',800)});text(ui.picks.length+' / 1 CHOSEN',innerWidth/2,innerHeight*.76,12,'#FFD36B');panel(innerWidth*.34,innerHeight*.80,innerWidth*.32,innerHeight*.13,.94);text('SET SAIL',innerWidth/2,innerHeight*.865,15,'#FFD36B','center',900);return;
  }
  if(compact){panel(innerWidth*.03,innerHeight*.04,innerWidth*.94,innerHeight*.92);text('OPENING WEAPONS - CHOOSE ONE',innerWidth/2,innerHeight*.10,11,'#7FC7D9');title('THE OPENING DRAFT',innerHeight*.16,27);text('One ability now. New skills arrive between waves.',innerWidth/2,innerHeight*.21,11,'#C9BC96');const x=innerWidth*.08,w=innerWidth*.84,h=innerHeight*.12;OPENING_SKILLS.forEach(([shape,element],i)=>{const y=innerHeight*(.28+i*.16),sd=SHAPES[shape],ed=ELEMENTS[element],active=chosen(shape+':'+element);panel(x,y,w,h,active?.92:.86);oc.strokeStyle=ed.color;oc.lineWidth=active?3:1;oc.strokeRect(x+7,y+7,w-14,h-14);text((i+1)+'. '+ed.name.toUpperCase()+' '+sd.name.toUpperCase(),x+w/2,y+34,14,ed.color,'center',900);text((sd.kind||'ability').toUpperCase()+' weapon',x+w/2,y+65,10,'#C9BC96');text(active?'SELECTED':'TAP TO CHOOSE',x+w/2,y+h-18,10,active?'#FFD36B':'#8A7B5C','center',800)});text(ui.picks.length+' / 1 CHOSEN',innerWidth/2,innerHeight*.79,14,'#FFD36B');panel(innerWidth*.25,innerHeight*.83,innerWidth*.50,innerHeight*.075,.94);text('SET SAIL',innerWidth/2,innerHeight*.868,17,'#FFD36B','center',900);return;
  }
  panel(innerWidth*.07,innerHeight*.12,innerWidth*.86,innerHeight*.70);text('OPENING WEAPONS - CHOOSE ONE',innerWidth/2,innerHeight*.19,15,'#7FC7D9');title('THE OPENING DRAFT',innerHeight*.28,40);text('Pick one ability. Your class weapon is already aboard; new skills arrive between waves.',innerWidth/2,innerHeight*.34,14,'#C9BC96');const w=Math.min(260,innerWidth*.25),h=Math.min(210,innerHeight*.30),gap=Math.min(26,innerWidth*.025),x0=(innerWidth-(w*3+gap*2))/2,y=innerHeight*.43;OPENING_SKILLS.forEach(([shape,element],i)=>{const x=x0+i*(w+gap),sd=SHAPES[shape],ed=ELEMENTS[element],active=chosen(shape+':'+element);panel(x,y,w,h,active?.92:.86);oc.strokeStyle=ed.color;oc.lineWidth=active?4:2;oc.strokeRect(x+10,y+10,w-20,h-20);text('WEAPON '+(i+1),x+w/2,y+34,12,'#7FC7D9');text(ed.name.toUpperCase(),x+w/2,y+72,18,ed.color,'center',900);text(sd.name.toUpperCase(),x+w/2,y+108,23,'#F0C878','center',900);text((sd.kind||'ability').toUpperCase()+' weapon',x+w/2,y+148,12,'#C9BC96');text(active?'SELECTED':'CHOOSE',x+w/2,y+h-24,12,active?'#FFD36B':'#8A7B5C','center',800)});text(ui.picks.length+' / 1 CHOSEN',innerWidth/2,innerHeight*.77,17,'#FFD36B');panel(innerWidth*.38,innerHeight*.82,innerWidth*.24,innerHeight*.075,.94);text('SET SAIL',innerWidth/2,innerHeight*.857,20,'#FFD36B','center',900);
}function drawWorkshop(){panel(innerWidth*.08,innerHeight*.07,innerWidth*.84,innerHeight*.86);text('WORKSHOP  ·  '+ui.meta.scrip+' SCRIP  ·  '+ui.meta.sigils+' SIGILS',innerWidth/2,innerHeight*.13,15,'#7FC7D9');title('THE WORKSHOP',innerHeight*.20,42);const entries=Object.entries(TALENTS).slice(0,12),cols=3,w=innerWidth*.25,h=innerHeight*.085,x0=innerWidth*.15,y0=innerHeight*.27;entries.forEach(([id,n],i)=>{const x=x0+(i%cols)*w,y=y0+Math.floor(i/cols)*h,rank=talentRank(ui.meta,id),open=canBuyTalent(ui.meta,id);panel(x,y,w-12,h-10,.86);text(n.name+'  '+rank+'/'+n.ranks,x+w/2-6,y+22,13,open?'#F0C878':'#8A7B5C');text(n.text,x+w/2-6,y+48,11,'#C9BC96')});text('ESC  BACK',innerWidth/2,innerHeight*.90,16,'#FFD36B')}
function drawHead(){if(ui.classId!=='boilerwright'||ui.mode!=='play')return;const w=220,x=innerWidth-245,y=innerHeight-112;panel(x,y,w,72,.82);text('HEAD',x+18,y+18,12,'#7FC7D9','left',800);oc.fillStyle='#17251f';oc.fillRect(x+18,y+32,w-36,12);oc.fillStyle='#56E5D5';oc.fillRect(x+18,y+32,(w-36)*ui.head/100,12);text(Math.floor(ui.head)+'%',x+w-18,y+18,12,'#DCD2B4','right',700);text('F  TAP MAIN   V  BLOWDOWN',x+w/2,y+58,10,'#C9BC96')}
function renderOverlay(){updateMobileVisibility();oc.clearRect(0,0,innerWidth,innerHeight);if(ui.mode==='class')drawClass();else if(ui.mode==='loadout')drawLoadout();else if(ui.mode==='workshop')drawWorkshop();else drawHead()}
function selectAt(x,y){
  const compact=innerWidth<600, short=innerHeight<560;
  if(ui.mode==='class'){
    if(short&&!compact){if(y>innerHeight*.32&&y<innerHeight*.76){ui.classId=x<innerWidth/2?'captain':'boilerwright';setMode('loadout')}}
    else if(compact){if(y>innerHeight*.20&&y<innerHeight*.82){ui.classId=y<innerHeight*.52?'captain':'boilerwright';setMode('loadout')}}
    else if(y>innerHeight*.37&&y<innerHeight*.72){ui.classId=x<innerWidth/2?'captain':'boilerwright';setMode('loadout')}
  }else if(ui.mode==='loadout'){
    if(short&&!compact){const w=innerWidth*.27,h=innerHeight*.34,gap=innerWidth*.03,x0=(innerWidth-(w*3+gap*2))/2,cy=innerHeight*.37;if(y>=cy&&y<=cy+h){const i=Math.floor((x-x0)/(w+gap));if(i>=0&&i<3&&x>=x0+i*(w+gap)&&x<=x0+i*(w+gap)+w){const key=OPENING_SKILLS[i].join(':');ui.picks=chosen(key)?[]:[key]}}if(y>innerHeight*.78&&ui.picks.length===1)launch()}
    else if(compact){const x0=innerWidth*.08,w=innerWidth*.84,h=innerHeight*.12;if(y>=innerHeight*.28&&y<=innerHeight*.28+h*3.2){const i=Math.floor((y-innerHeight*.28)/(innerHeight*.16));if(i>=0&&i<3){const key=OPENING_SKILLS[i].join(':');ui.picks=chosen(key)?[]:[key]}}if(y>innerHeight*.82&&ui.picks.length===1)launch()}
    else{const w=Math.min(260,innerWidth*.25),h=Math.min(210,innerHeight*.30),gap=Math.min(26,innerWidth*.025),x0=(innerWidth-(w*3+gap*2))/2,cy=innerHeight*.43;if(y>=cy&&y<=cy+h){const i=Math.floor((x-x0)/(w+gap));if(i>=0&&i<3&&x>=x0+i*(w+gap)&&x<=x0+i*(w+gap)+w){const key=OPENING_SKILLS[i].join(':');ui.picks=chosen(key)?[]:[key]}}if(y>innerHeight*.80&&ui.picks.length===1)launch()}
  }else if(ui.mode==='workshop'){if(y>innerHeight*.85)resetOverlay();else{const entries=Object.entries(TALENTS).slice(0,12),cols=3,w=innerWidth*.25,h=innerHeight*.085,x0=innerWidth*.15,y0=innerHeight*.27,i=Math.floor((y-y0)/h)*cols+Math.floor((x-x0)/w);if(entries[i]&&canBuyTalent(ui.meta,entries[i][0])){buyTalent(ui.meta,entries[i][0]);saveMeta(ui.meta)}}}
}function update(){if(ui.mode==='play'){if(ui.classId==='boilerwright'&&S.player){const onVent=Math.hypot(S.player.x-560,S.player.y-300)<75||Math.hypot(S.player.x-840,S.player.y-300)<75;const still=Math.hypot(S.player.vx,S.player.vy)<18;ui.head=clamp(ui.head+(onVent&&still?.75:.0),0,100);S.head=ui.head;const want=ui.head>0;if(want&&!ui.boosted){for(const sk of S.slots)if(sk)sk.mods.dmg*=1.45;ui.boosted=true}if(!want&&ui.boosted){for(const sk of S.slots)if(sk)sk.mods.dmg/=1.45;ui.boosted=false}}if((S.mode==='victory'||S.mode==='gameover')&&!ui.awarded){ui.awarded=true;const row={date:new Date().toISOString(),build:'classic-v1-parity',seed:'classic',won:S.mode==='victory',wave:S.wave,classId:ui.classId,heat:ui.meta.heat,time:'',kills:S.stats?.kills||0,damage:Math.round(S.stats?.damage||0),deckDamage:0,allyDamage:0,salvage:0,vents:0,healed:0,taken:0,closeShare:0,midShare:0,farShare:0,cards:S.stats?.cards||[],ship:[]};awardRun(ui.meta,row);saveMeta(ui.meta)}}renderOverlay();requestAnimationFrame(update)}
overlay.addEventListener('mousedown',e=>{if(e.button!==0)return;e.preventDefault();if(ui.mode==='title'){setMode('class');return}if(ui.mode!=='play')selectAt(e.clientX,e.clientY)});
overlay.addEventListener('touchstart',e=>{const t=e.changedTouches[0];if(!t)return;e.preventDefault();if(ui.mode==='title'){setMode('class');return}if(ui.mode!=='play')selectAt(t.clientX,t.clientY)},{passive:false});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(ui.mode==='loadout'&&/^[1-3]$/.test(k)){const key=OPENING_SKILLS[Number(k)-1].join(':');ui.picks=chosen(key)?[]:[key];e.preventDefault();return}if(ui.mode==='loadout'&&k==='enter'&&ui.picks.length===1){launch();e.preventDefault();return}if(k==='escape'&&ui.mode!=='title'){e.preventDefault();e.stopImmediatePropagation();resetOverlay();return}if(k==='o'&&ui.mode==='title'){e.preventDefault();e.stopImmediatePropagation();setMode('workshop');return}if(ui.mode==='play'&&ui.classId==='boilerwright'&&S.mode==='play'){if(k==='f'){e.preventDefault();e.stopImmediatePropagation();if(ui.head>=10){ui.head-=10;G.castSlot(0,{free:true})}}if(k==='v'){e.preventDefault();e.stopImmediatePropagation();if(ui.head>=20){ui.head=0;G.castSlot(1,{free:true})}}if(k===' '&&ui.head>=12){e.preventDefault();e.stopImmediatePropagation();ui.head-=12;S.player.dashStock=Math.max(1,S.player.dashStock);S.player.dashCd=0;S.player.dashT=.22;S.player.dashAng=S.player.aim}}},true);
window.__v1Parity=ui;setMode('title');installData();requestAnimationFrame(update);
