import {ARTICLES,CLASSES,ELEMENTS,HEAT,SHAPES,TALENTS,WAVES,makeSkill} from './parity-data.js';
import {awardRun,buyArticle,buyTalent,canBuyArticle,canBuyTalent,freshMeta,loadMeta,saveMeta,talentRank} from './parity-systems.js';

const G=window.SKYGEAR,S=G.S,cv=document.getElementById('c');
const ui={mode:'title',classId:'captain',picks:[],meta:loadMeta(),head:0,boosted:false,awarded:false};
const overlay=document.createElement('canvas');overlay.id='v1-parity-ui';Object.assign(overlay.style,{position:'fixed',inset:'0',width:'100vw',height:'100vh',pointerEvents:'auto',zIndex:'10'});document.body.append(overlay);const oc=overlay.getContext('2d');
const fit=()=>{const d=Math.min(devicePixelRatio||1,2);overlay.width=innerWidth*d;overlay.height=innerHeight*d;oc.setTransform(d,0,0,d,0,0)};addEventListener('resize',fit);fit();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function setMode(m){ui.mode=m;overlay.style.pointerEvents=m==='play'?'none':'auto';S.mode=m==='play'?'play':m==='title'?'title':'parity-'+m}
function text(t,x,y,size=16,color='#F0C878',align='center',weight=700){oc.font=`${weight} ${size}px Trebuchet MS,system-ui,sans-serif`;oc.textAlign=align;oc.textBaseline='middle';oc.fillStyle=color;oc.fillText(t,x,y)}
function panel(x,y,w,h,alpha=.92){oc.save();oc.fillStyle=`rgba(23,16,12,${alpha})`;oc.strokeStyle='#D4A648';oc.lineWidth=3;oc.beginPath();oc.roundRect(x,y,w,h,12);oc.fill();oc.stroke();oc.strokeStyle='rgba(255,220,130,.28)';oc.lineWidth=1;oc.strokeRect(x+7,y+7,w-14,h-14);oc.restore()}
function title(t,y,size=32){text(t,innerWidth/2,y,size,'#F0C878','center',900)}
function currentClass(){return CLASSES[ui.classId]}
function installData(){
  Object.assign(G.SHAPES,{AURA:{key:'AURA',noun:'Field',kind:'arc',desc:'persistent field around the captain',range:150,arc:Math.PI*2,dmg:4,cd:1.8,knock:25},PULSE:{key:'PULSE',noun:'Pulse',kind:'aoe',desc:'radial pressure burst',radius:210,castRange:260,dmg:34,cd:4.4,knock:220},SENTRY:{key:'SENTRY',noun:'Sentry',kind:'aoe',desc:'deployable deck sentry',radius:30,castRange:520,dmg:14,cd:9,knock:70}});
  const converted=WAVES.map((w,i)=>({boss:i===11,batches:(w.batches||[]).map(b=>[b[0],b[1],b[2]]),loop:i===11?{every:9.5,sets:[['SWARM',5],['SCRAPPER',4],['GUNNER',3]]}:undefined}));
  G.WAVES.splice(0,G.WAVES.length,...converted);
}
function resetOverlay(){ui.classId='captain';ui.picks=[];ui.head=0;ui.boosted=false;ui.awarded=false;setMode('title')}
function chosen(key){return ui.picks.includes(key)}
function launch(){
  const c=currentClass(),t=ui.meta.nodes||{};
  G.TUNING.player.hp=c.hp+(talentRank(ui.meta,'padded_coat')*8||0);G.TUNING.player.speed=c.speed;G.TUNING.player.dashCharges=c.dashes;
  G.startRun();S.classId=ui.classId;S.className=c.name;S.classData=c;S.slots=ui.picks.map(k=>{const[a,b]=k.split(':');return G.newSkill(a,b)});while(S.slots.length<4)S.slots.push(G.newSkill('LINE_BURST','EMBER'));S.unlockedSlots=4;S.mods.dashCharges=c.dashes;S.player.dashStock=c.dashes;S.player.maxHp=c.hp;S.player.hp=c.hp;setMode('play');
}
function drawClass(){panel(innerWidth*.1,innerHeight*.18,innerWidth*.8,innerHeight*.64);text('CHOOSE WHO HOLDS THE DECK',innerWidth/2,innerHeight*.25,15,'#7FC7D9','center',800);title('THE ARTICLES OF COMMAND',innerHeight*.32,44);const cards=[['captain',.18],['boilerwright',.52]];for(const[id,xr]of cards){const c=CLASSES[id],x=innerWidth*xr,y=innerHeight*.39,w=innerWidth*.30,h=innerHeight*.27;panel(x,y,w,h,.88);text(c.gauge+'  ·  '+c.hp+' HP  ·  '+c.speed+' SPEED',x+w/2,y+28,13,'#7FC7D9');text(c.name,x+w/2,y+66,25,'#F0C878','center',900);text(c.blurb,x+w/2,y+106,14,'#DCD2B4');text(c.compare.question,x+w/2,y+142,13,'#C9BC96');text(c.compare.payoff,x+w/2,y+174,12,'#C9BC96') }text('CLICK A CAPTAIN',innerWidth/2,innerHeight*.75,16,'#FFD36B','center',800)}
function drawLoadout(){panel(innerWidth*.06,innerHeight*.07,innerWidth*.88,innerHeight*.86);text('OPENING WEAPONS  ·  CHOOSE FOUR',innerWidth/2,innerHeight*.12,15,'#7FC7D9');title('THE OPEN MATRIX',innerHeight*.18,40);text('36 shape x element combinations. Every chosen cell is live in the V1 deck.',innerWidth/2,innerHeight*.23,14,'#C9BC96');const x0=innerWidth*.12,y0=innerHeight*.28,w=innerWidth*.76/4,h=innerHeight*.048;let n=0;for(const[shape,sd]of Object.entries(SHAPES)){for(const[element,ed]of Object.entries(ELEMENTS)){const key=shape+':'+element,x=x0+(n%4)*w,y=y0+Math.floor(n/4)*h;oc.fillStyle=chosen(key)?'rgba(92,58,26,.95)':'rgba(38,30,23,.92)';oc.strokeStyle=ed.color;oc.lineWidth=chosen(key)?3:1;oc.fillRect(x+3,y+3,w-6,h-6);oc.strokeRect(x+3,y+3,w-6,h-6);text(sd.name+'  ·  '+ed.name,x+w/2,y+h/2,11,ed.color);n++}}text(`${ui.picks.length} / 4 CHOSEN`,innerWidth/2,innerHeight*.78,17,'#FFD36B');panel(innerWidth*.38,innerHeight*.82,innerWidth*.24,innerHeight*.075,.94);text('SET SAIL',innerWidth/2,innerHeight*.857,20,'#FFD36B','center',900)}
function drawWorkshop(){panel(innerWidth*.08,innerHeight*.07,innerWidth*.84,innerHeight*.86);text('WORKSHOP  ·  '+ui.meta.scrip+' SCRIP  ·  '+ui.meta.sigils+' SIGILS',innerWidth/2,innerHeight*.13,15,'#7FC7D9');title('THE WORKSHOP',innerHeight*.20,42);const entries=Object.entries(TALENTS).slice(0,12),cols=3,w=innerWidth*.25,h=innerHeight*.085,x0=innerWidth*.15,y0=innerHeight*.27;entries.forEach(([id,n],i)=>{const x=x0+(i%cols)*w,y=y0+Math.floor(i/cols)*h,rank=talentRank(ui.meta,id),open=canBuyTalent(ui.meta,id);panel(x,y,w-12,h-10,.86);text(n.name+'  '+rank+'/'+n.ranks,x+w/2-6,y+22,13,open?'#F0C878':'#8A7B5C');text(n.text,x+w/2-6,y+48,11,'#C9BC96')});text('ESC  BACK',innerWidth/2,innerHeight*.90,16,'#FFD36B')}
function drawHead(){if(ui.classId!=='boilerwright'||ui.mode!=='play')return;const w=220,x=innerWidth-245,y=innerHeight-112;panel(x,y,w,72,.82);text('HEAD',x+18,y+18,12,'#7FC7D9','left',800);oc.fillStyle='#17251f';oc.fillRect(x+18,y+32,w-36,12);oc.fillStyle='#56E5D5';oc.fillRect(x+18,y+32,(w-36)*ui.head/100,12);text(Math.floor(ui.head)+'%',x+w-18,y+18,12,'#DCD2B4','right',700);text('F  TAP MAIN   V  BLOWDOWN',x+w/2,y+58,10,'#C9BC96')}
function renderOverlay(){oc.clearRect(0,0,innerWidth,innerHeight);if(ui.mode==='class')drawClass();else if(ui.mode==='loadout')drawLoadout();else if(ui.mode==='workshop')drawWorkshop();else drawHead()}
function selectAt(x,y){if(ui.mode==='class'){if(y>innerHeight*.37&&y<innerHeight*.72){ui.classId=x<innerWidth/2?'captain':'boilerwright';setMode('loadout');}}else if(ui.mode==='loadout'){const x0=innerWidth*.12,y0=innerHeight*.28,w=innerWidth*.76/4,h=innerHeight*.048;if(y>=y0&&y<y0+h*36){const i=Math.floor((y-y0)/h)*4+Math.floor((x-x0)/w);if(i>=0&&i<36){const shape=Object.keys(SHAPES)[Math.floor(i/4)],element=Object.keys(ELEMENTS)[i%4],key=shape+':'+element;if(chosen(key))ui.picks=ui.picks.filter(v=>v!==key);else if(ui.picks.length<4)ui.picks.push(key)}}if(y>innerHeight*.80&&ui.picks.length===4)launch();}else if(ui.mode==='workshop'){if(y>innerHeight*.85)resetOverlay();else{const entries=Object.entries(TALENTS).slice(0,12),cols=3,w=innerWidth*.25,h=innerHeight*.085,x0=innerWidth*.15,y0=innerHeight*.27,i=Math.floor((y-y0)/h)*cols+Math.floor((x-x0)/w);if(entries[i]&&canBuyTalent(ui.meta,entries[i][0])){buyTalent(ui.meta,entries[i][0]);saveMeta(ui.meta)}}}}
function update(){if(ui.mode==='play'){if(ui.classId==='boilerwright'&&S.player){const onVent=Math.hypot(S.player.x-560,S.player.y-300)<75||Math.hypot(S.player.x-840,S.player.y-300)<75;const still=Math.hypot(S.player.vx,S.player.vy)<18;ui.head=clamp(ui.head+(onVent&&still?.75:.0),0,100);const want=ui.head>0;if(want&&!ui.boosted){for(const sk of S.slots)if(sk)sk.mods.dmg*=1.45;ui.boosted=true}if(!want&&ui.boosted){for(const sk of S.slots)if(sk)sk.mods.dmg/=1.45;ui.boosted=false}}if((S.mode==='victory'||S.mode==='gameover')&&!ui.awarded){ui.awarded=true;const row={date:new Date().toISOString(),build:'classic-v1-parity',seed:'classic',won:S.mode==='victory',wave:S.wave,classId:ui.classId,heat:ui.meta.heat,time:'',kills:S.stats?.kills||0,damage:Math.round(S.stats?.damage||0),deckDamage:0,allyDamage:0,salvage:0,vents:0,healed:0,taken:0,closeShare:0,midShare:0,farShare:0,cards:S.stats?.cards||[],ship:[]};awardRun(ui.meta,row);saveMeta(ui.meta)}}renderOverlay();requestAnimationFrame(update)}
overlay.addEventListener('mousedown',e=>{if(e.button!==0)return;e.preventDefault();if(ui.mode==='title'){setMode('class');return}if(ui.mode!=='play')selectAt(e.clientX,e.clientY)});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(ui.mode==='loadout'&&/^[1-9]$/.test(k)){const i=Number(k)-1,shape=Object.keys(SHAPES)[Math.floor(i/4)],element=Object.keys(ELEMENTS)[i%4],key=shape+':'+element;if(chosen(key))ui.picks=ui.picks.filter(v=>v!==key);else if(ui.picks.length<4)ui.picks.push(key);e.preventDefault();return}if(ui.mode==='loadout'&&k==='enter'&&ui.picks.length===4){launch();e.preventDefault();return}if(k==='escape'&&ui.mode!=='title'){e.preventDefault();e.stopImmediatePropagation();resetOverlay();return}if(k==='o'&&ui.mode==='title'){e.preventDefault();e.stopImmediatePropagation();setMode('workshop');return}if(ui.mode==='play'&&ui.classId==='boilerwright'&&S.mode==='play'){if(k==='f'){e.preventDefault();e.stopImmediatePropagation();if(ui.head>=10){ui.head-=10;G.castSlot(0,{free:true})}}if(k==='v'){e.preventDefault();e.stopImmediatePropagation();if(ui.head>=20){ui.head=0;G.castSlot(1,{free:true})}}if(k===' '&&ui.head>=12){e.preventDefault();e.stopImmediatePropagation();ui.head-=12;S.player.dashStock=Math.max(1,S.player.dashStock);S.player.dashCd=0;S.player.dashT=.22;S.player.dashAng=S.player.aim}}},true);
window.__v1Parity=ui;setMode('title');installData();requestAnimationFrame(update);
