/* GENERATED by src/ingest-audio.py — do not edit.
   What audio actually exists in the repo, and in how many takes. The
   loader fetches only what is named here, so an undelivered cue costs
   no request and logs no 404; it simply keeps its procedural voice. */
const AUDIO_DELIVERED = {
  "amb_ship": {
    "ext": ".ogg",
    "n": 1
  },
  "amb_storm": {
    "ext": ".ogg",
    "n": 1
  },
  "boiler_critical": {
    "ext": ".ogg",
    "n": 1
  },
  "boiler_hurt": {
    "ext": ".ogg",
    "n": 1
  },
  "boss_roar": {
    "ext": ".ogg",
    "n": 1
  },
  "cannon_down": {
    "ext": ".ogg",
    "n": 3
  },
  "cannon_fire": {
    "ext": ".ogg",
    "n": 3
  },
  "cannon_hurt": {
    "ext": ".ogg",
    "n": 3
  },
  "card_deal": {
    "ext": ".ogg",
    "n": 1
  },
  "card_pick": {
    "ext": ".ogg",
    "n": 1
  },
  "climb": {
    "ext": ".ogg",
    "n": 1
  },
  "crate_break": {
    "ext": ".ogg",
    "n": 2
  },
  "crew_attack": {
    "ext": ".ogg",
    "n": 3
  },
  "crew_down": {
    "ext": ".ogg",
    "n": 2
  },
  "crew_muster": {
    "ext": ".ogg",
    "n": 1
  },
  "crit": {
    "ext": ".ogg",
    "n": 3
  },
  "crossing": {
    "ext": ".ogg",
    "n": 1
  },
  "dash": {
    "ext": ".ogg",
    "n": 1
  },
  "death_heavy": {
    "ext": ".ogg",
    "n": 2
  },
  "death_light": {
    "ext": ".ogg",
    "n": 3
  },
  "elem_ARC": {
    "ext": ".ogg",
    "n": 1
  },
  "elem_EMBER": {
    "ext": ".ogg",
    "n": 1
  },
  "elem_FROST": {
    "ext": ".ogg",
    "n": 1
  },
  "elem_STEAM": {
    "ext": ".ogg",
    "n": 1
  },
  "hit": {
    "ext": ".ogg",
    "n": 5
  },
  "hulk_break": {
    "ext": ".ogg",
    "n": 1
  },
  "hulk_grapple": {
    "ext": ".ogg",
    "n": 1
  },
  "hulk_hit": {
    "ext": ".ogg",
    "n": 1
  },
  "hurt": {
    "ext": ".ogg",
    "n": 1
  },
  "keg_blow": {
    "ext": ".ogg",
    "n": 1
  },
  "keg_fuse": {
    "ext": ".ogg",
    "n": 1
  },
  "lantern_break": {
    "ext": ".ogg",
    "n": 1
  },
  "m_boss": {
    "ext": ".mp3",
    "n": 1
  },
  "m_combat1": {
    "ext": ".mp3",
    "n": 1
  },
  "m_combat3": {
    "ext": ".mp3",
    "n": 1
  },
  "pickup": {
    "ext": ".ogg",
    "n": 1
  },
  "ready": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_beam_end": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_beam_loop": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_beam_start": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_cleave": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_gale": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_lance": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_mortar": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_mortar_land": {
    "ext": ".ogg",
    "n": 1
  },
  "shape_whip": {
    "ext": ".ogg",
    "n": 1
  },
  "shoot_drone": {
    "ext": ".ogg",
    "n": 1
  },
  "slam": {
    "ext": ".ogg",
    "n": 1
  },
  "slot_unlock": {
    "ext": ".ogg",
    "n": 1
  },
  "telegraph": {
    "ext": ".ogg",
    "n": 1
  },
  "ui_click": {
    "ext": ".ogg",
    "n": 1
  },
  "ui_hover": {
    "ext": ".ogg",
    "n": 1
  },
  "vent": {
    "ext": ".ogg",
    "n": 1
  },
  "vo_boiler_low": {
    "ext": ".ogg",
    "n": 3
  },
  "vo_boss_arrive": {
    "ext": ".ogg",
    "n": 2
  },
  "vo_boss_turn": {
    "ext": ".ogg",
    "n": 2
  },
  "vo_cannon_down": {
    "ext": ".ogg",
    "n": 3
  },
  "vo_crew_down": {
    "ext": ".ogg",
    "n": 6
  },
  "vo_crew_muster": {
    "ext": ".ogg",
    "n": 4
  },
  "vo_dash": {
    "ext": ".ogg",
    "n": 6
  },
  "vo_defeat": {
    "ext": ".ogg",
    "n": 3
  },
  "vo_draft": {
    "ext": ".ogg",
    "n": 3
  },
  "vo_first_board": {
    "ext": ".ogg",
    "n": 3
  },
  "vo_hurt_low": {
    "ext": ".ogg",
    "n": 4
  },
  "vo_keg": {
    "ext": ".ogg",
    "n": 4
  },
  "vo_lane_critical": {
    "ext": ".ogg",
    "n": 4
  },
  "vo_push": {
    "ext": ".ogg",
    "n": 3
  },
  "vo_slot": {
    "ext": ".ogg",
    "n": 3
  },
  "vo_vent": {
    "ext": ".ogg",
    "n": 4
  },
  "vo_victory": {
    "ext": ".ogg",
    "n": 2
  },
  "vo_wave_clear": {
    "ext": ".ogg",
    "n": 4
  },
  "vo_wave_start": {
    "ext": ".ogg",
    "n": 4
  },
  "wave_clear": {
    "ext": ".ogg",
    "n": 1
  },
  "wave_start": {
    "ext": ".ogg",
    "n": 1
  }
};
