/* GENERATED by src/ingest-audio.py — do not edit.
   What audio actually exists in the repo, and in how many takes. The
   loader fetches only what is named here, so an undelivered cue costs
   no request and logs no 404; it simply keeps its procedural voice. */
const AUDIO_DELIVERED = {
  "cannon_down": {
    "ext": ".wav",
    "n": 3
  },
  "cannon_fire": {
    "ext": ".wav",
    "n": 3
  },
  "cannon_hurt": {
    "ext": ".wav",
    "n": 3
  },
  "crew_muster": {
    "ext": ".wav",
    "n": 2
  },
  "hit": {
    "ext": ".wav",
    "n": 5
  },
  "m_boss": {
    "ext": ".mp3",
    "n": 1
  },
  "m_combat1": {
    "ext": ".mp3",
    "n": 1
  },
  "m_combat3": {
    "ext": ".mp3",
    "n": 1
  }
};
